### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by Becojo** [marcobambini/gravity#1]
I had a couple issues while compiling Gravity on Ubuntu. Here's what I did to make it compile:

1. add `#include <stdint.h>` to the top of debug_macros.h
2. set `LDFLAGS = -lm` in the Makefile for some math functions such as ceil and pow.

Hope this helps.

**Comment by mihai303** [comment]
In addition to the previous comment I had to add -std=gnu99 to the CFLAGS in the Makefile in order to compile the sources on an arm box (cubox-i) under Debian Jessie. Please note that all test pass as well after the changes.

**Comment by marcobambini** [comment]
Thanks @Becojo and @mihai303, I just added all the changes and I can confirm that it builds on Linux 64 bit and all unit test are successfully passed.
