### ISSUE TITLE
why not swift?

### ISSUE THREAD

**Issue by sebbean** [marcobambini/gravity#10]
just curious, you mentioned its similar. Since swift is open source.. couldn't you utilize it however you'd like?

guess i'm always curious when a new language comes out as to the pros and cons of yet another language on the market with some slight differences to all the others out there.

**Comment by nickbauman** [comment]
Swift has a huge runtime. Building a "hello world" service using the Swift runtime is over 2 gigs. A similar Python one is around 200 megs.
