### ISSUE TITLE
range.loop

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#102]
I noticed in the docs that you can do something like this:

```swift
var target = 0...5
target.loop(func (value) { System.print(value) } )
```

but something like this doesn't seem to work:

```swift
0...5.loop(func (value) { System.print(value) } )
```

I think that gravity interprets this as:

```swift
5.loop(func (value) { System.print(value) } )
```

because it doesn't do the loop with a value of `5`, and that code doesn't seem to every go into the range_loop function in gravity_core.c.

I am not sure if this was  a design choice or not, but I think it would be useful to be able to just do `0...5.loop(func (value) ...`

**Comment by marcobambini** [comment]
You are right but I am not sure about the best way to proceed.
The behavior is a consequence of the Pratt parser operators precedences and it is right that a dot call expression (.) has higher precedence than a range expression (...), I noticed that others languages exhibit the same issue.

As a workaround you can use:
(0...5).loop(func (value) { System.print(value) } )

I'll think a bit more about it, thanks for the report!
