### ISSUE TITLE
Built in Sort

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#104]
It might be useful to have some kind of built in sorting algorithm for things like lists (and maybe a reverse):

```swift
var list = [2, 4, 1, 5, 3]
list.sort() // returns [1, 2, 3, 4, 5]
list.sort().reverse() // returns [5, 4, 3, 2, 1]
```

if this is something that may make it's way into gravity it is probably worth thinking about what would happen in the event that a list contains numbers and strings, or if we want other things to be sorted as well, such as maybe a list of objects sorted by a specific field.

Also what sorting algorithm would be used. I have heard that for example, python uses Timsort.

**Comment by marcobambini** [comment]
Yes I agree that it would be really useful.

Things are easy when the list contains elements of the same type but became a little obscure when different types are contained. A list can contain numbers, strings, functions, classes and any kind of objects.

A simple algorithm would be to manage the number/string case in the traditional way and sort any other object by its hash.

**Comment by kngu9** [comment]
The best general sorting algorithm for arbitrary data would be quicksort, which has O(n^2) but is theta(nlogn). 

@marcobambini The best way to do this is to make a callback function, so the developer can decide how to convert it.

`
func sort_func(a, b) {
    return a > b
}

var list = [1, 2, 3, 'a', 'b', 'c']
list.sort(sort_func)
`

**Comment by neysofu** [comment]
See [this](https://stackoverflow.com/questions/7770230/comparison-between-timsort-and-quicksort) discussion for a comparison of Timsort and Quicksort.

I also think that allowing implicit ordering between types is a bad idea and it would be better to pass an explicit ordering function.

**Comment by marcobambini** [comment]
Anyone is interested in working on this feature?

**Comment by MatanSilver** [comment]
I've got a working reverse function and I can take a crack at a sort too if you like. I'm a bit new to writing for compilers but I can give it a shot...

**Comment by marcobambini** [comment]
@MatanSilver your contribution would be more than welcomed :-)

**Comment by MatanSilver** [comment]
Presumably we want sort and reverse to return new list objects and not modify the ones they are called on?

**Comment by marcobambini** [comment]
That's a good question. Swift uses sort() to modify the original array while sorted() returns a new array:  [https://developer.apple.com/documentation/swift/array/1688499-sort](https://developer.apple.com/documentation/swift/array/1688499-sort) I think we can follow the same behaviour.

**Comment by MatanSilver** [comment]
So I guess the analogy for reverse would be reverse() modifying the array and reversed() returning a new one?

**Comment by marcobambini** [comment]
Thanks a lot to @MatanSilver for his contribution.
