### ISSUE TITLE
Returning Lists?

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#105]
Should we be able to return a list from main? Because I am not able to do this

```swift
func main() {
  return [1, 2, 3, 4]
}
```

```bash
$ gravity test.gravity 
RESULT: (LIST) N/A (in 0.0019 ms)
```

**Comment by marcobambini** [comment]
The list is correctly returned (as you can see from the LIST string in result).
gravity.c calls gravity_value_dump that simply dump the LIST type and don't recursively dump each list item.

**Comment by hallzy** [comment]
okay thanks.
