### ISSUE TITLE
Suggestion: Raw Strings

### ISSUE THREAD

**Issue by Jezza** [marcobambini/gravity#109]
The ability to declare a portion of the file as a raw string would be convenient.
This would also play really well with string interpolation: #45 

example:
```
return ```${name} = function() {
  console.log('${message}');
}```
```

**Comment by marcobambini** [comment]
I am not sure to understand...

**Comment by Armored-Dragon** [comment]
Raw string literals.
In a raw string literal, you can span a string over multiple lines for a multiline string.
The other main point is that escapes aren't parsed in raw strings.

In C++14 for example, a raw string can be created with
```cpp
std::string example = r"(
This is the content of the raw string.
)";```
In python,
```py
example = r'''
This is the content of the raw string.'''```
example = r'
This is the content of the raw string.'

**Comment by marcobambini** [comment]
It seems like we would need another syntax in order to support raw strings, probably a simple Python like notation could work:
```swift
var a = '''This is the content
of the raw string.'''
```

**Comment by marcobambini** [comment]
@Armored-Dragon please note that Gravity already supports newlines inside a string literal:
```swift
var s = "this is a String
that contains a newline"
```

**Comment by marcobambini** [comment]
Feature request moved to low priority wiki page: https://github.com/marcobambini/gravity/wiki/Low-priority-features
