### ISSUE TITLE
Ability to pass arguments to a gravity script

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#113]
for instance:

```bash
gravity add.gravity 2 4 5
```

Should return "11" assuming the code is something like:

```swift
func main() {
  var sum = 0
  _args.loop(func (value) {
    sum += value
  })
  return sum
}
```

Basically, just a way to get values from the command line would be quite useful

**Comment by marcobambini** [comment]
Feature request moved to low priority wiki page: https://github.com/marcobambini/gravity/wiki/Low-priority-features

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/11efd1596a602c309339e902e6a16f080b885b2f
