### ISSUE TITLE
break and continue don't work in loop method

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#114]
Not sure if this was a design decision or not, but break and continue statements appear to not work in the loop() method (obviously, having continue in this code is pointless, but it is just as an example):

```swift
  list = 0...4
  list.loop(func(value) {
    System.print(value)
    continue
  })
```
Running the above code returns:

```bash
SEMANTIC ERROR on 0 (16,5): 'continue' statement not in loop statement.
```

Same goes for `break`

**Comment by hallzy** [comment]
i mean, given that it seems to really just be a function that is called in a loop, I guess it makes sense to say that it isn't actually in a loop, its function is just being called multiple times with different values.

Initially it just seemed like the kind of thing that should be doable, so I thought I would bring it up and just check if it was planned out this way or not

**Comment by marcobambini** [comment]
Recognized loops are the ones enclosed in keywords for, while and repeat.
list.loop is just a function call and cannot be recognized as a standard loop by the compiler.
