### ISSUE TITLE
Characters after the last interpolated string to not appear

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#117]
I noticed that the characters after the last interpolated string variable do not get displayed.

Take for example the `Vector` class on the main page of gravity when it calls the `String()` method:

```swift
return v3.String();
```

When I run this code I get:

```bash
RESULT: (STRING) [5,7,9 (0x1e4f4f0) (in 0.0236 ms)
```

Noting that the last `]` is missing from the string.

**Comment by marcobambini** [comment]
Thanks for the report.
Fixed by https://github.com/marcobambini/gravity/commit/d24fa50d12abf1c2daae1cec3b9288150976bf4e
