### ISSUE TITLE
Segmentation fault on unknown function call

### ISSUE THREAD

**Issue by kovetskiy** [marcobambini/gravity#12]
Hi, when I've called unknown function on `System` object I've got segmentation fault.

Reproduce:

test.gravity
```
func main() {
    System.unknown_function();
}
```

run:
```
./gravity test.gravity
[1]    24208 segmentation fault (core dumped)  ./gravity test.gravity
```

Also which extension of gravity files I should use? `.gravity`/`.gr` or something else?

**Comment by marcobambini** [comment]
Thanks @kovetskiy, I just fixed the issue.
I think .gravity for source code and .gr for compiled files.
