### ISSUE TITLE
2017-04-05 Segmentation Fauls

### ISSUE THREAD

**Issue by rwhitworth** [marcobambini/gravity#120]
After the last changes afl-fuzz was able to detect more segmentation faults.  Do you care to check these out as well?

https://github.com/rwhitworth/gravity-fuzz/tree/master/2017-04-05

I'm going to have to learn gravity so I can produce more useful test cases for it :-)

**Comment by marcobambini** [comment]
I am really interested in solving this issues, thanks!
I am going to fix all of them in my morning.

**Comment by blindfuzzy** [comment]
I have about 85-90% code coverage fuzzing 'gravity' right now. @rwhitworth we should team up and start analyzing these crashes if you're interested so that we may submit actual "bugs" versus just afl output.

**Comment by marcobambini** [comment]
@rwhitworth It has been hard! But all fixed by https://github.com/marcobambini/gravity/commit/aee9746bac1f75096ff8d840d4c7786a13bdd9b7
