### ISSUE TITLE
Bug,Error Fiber.yield()!

### ISSUE THREAD

**Issue by questionpython** [marcobambini/gravity#124]
input : 
```
func main() {
	var fiber = Fiber.create({
		System.print("fiber 1");
		Fiber.yield()
		System.print("fiber 2");
	});

	System.print("main 1");
	fiber()
	System.print("main 2");
	fiber()
	System.print("main 3");
}
```
$ ./gravity input
-----------

>main 1
fiber 1
Segmentation fault (core dumped)

**Comment by marcobambini** [comment]
Thanks a lot for the report @questionpython!
Fixed by https://github.com/marcobambini/gravity/commit/6e59d782ea16eedf86c701be39fbab0ce26ff48b
