### ISSUE TITLE
Standalone binary output

### ISSUE THREAD

**Issue by YurySolovyov** [marcobambini/gravity#125]
I did a quick (maybe too quick) search on GH and docs, but didn't found a way to compile Gravity program into a standalone binary.
By standalone I don't mean for all platforms of course, just being able to run compiled programs without compiling Gravity itself.

**Comment by marcobambini** [comment]
In the current version there is no way to output a standalone executable file.

**Comment by YurySolovyov** [comment]
What's the recommended way of distributing then?

**Comment by marcobambini** [comment]
A compiled gravity file that can run with gravity executable.
