### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by YurySolovyov** [marcobambini/gravity#128]
Creating a ticket for Wiki page entry :smile: 

I don't think Travis supports Windows ATM, but we can use other free CI plaforms.

The question is, given clean windows machine, what dependencies should we install and which commands to run?

**Comment by marcobambini** [comment]
I am not a Windows expert but I think that the only real needed dependency is the C runtime system.
The command to run should be the unittest (as we did on Mac/Linux).

**Comment by YurySolovyov** [comment]
Default build on Appveyor seem to produce a lot of errors: [log.txt](https://github.com/marcobambini/gravity/files/911121/log.txt)

**Comment by marcobambini** [comment]
Does the Visual C project itself works fine?

**Comment by YurySolovyov** [comment]
Had no chance to test it locally yet

**Comment by zilluss** [comment]
I get the same errors when I try to build it locally, the Visual Studio solution isn't working for me at all (tested with VS 2017).

**Comment by zilluss** [comment]
Another issue I found was that the VS Compiler doesnt support variable length arrays (like so: https://github.com/marcobambini/gravity/blob/a39c6a461d1e714c63e3ea575be64d83375cc354/src/runtime/gravity_core.c#L1721)
