### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by blindfuzzy** [marcobambini/gravity#139]
@marcobambini is there anyway @tylerp96 and myself could get a copy of gravity prior to all the changes? I don't know if you happen to have one laying around somewhere.

**Comment by marcobambini** [comment]
@blindfuzzy @tylerp96 I think you could just checkout Gravity until a specific commit:
http://stackoverflow.com/questions/2007662/rollback-to-an-old-git-commit-in-a-public-repo
