### ISSUE TITLE
Warning C4047 for macro UNDEF_TOKEN

### ISSUE THREAD

**Issue by dxramax** [marcobambini/gravity#141]
when compiling gravity using Visual Studio 2017 Community, the below warning appears 
`Warning	C4047	'initializing': 'bool' differs in levels of indirection from 'void *'` for the macro UNDEF_TOKEN in token.h.

when changing the macro to 
`#define UNDEF_TOKEN				(token_s){TOK_KEY_UNDEFINED,0,0,0,0,0,0,0}`
the warning disappear.

the compiler issue the warning for the initialing the token_s.value to NULL which is `((void *)0)` in c environment, in CPP it's 0 so the warning don't appears.

also the macro NO_TOKEN same story.

**Comment by marcobambini** [comment]
I don't think you have the latest version because the definition in the latest repo is now:
```c
#define NO_TOKEN        (gtoken_s){0,0,0,0,0,0,0,0,NULL}
#define UNDEF_TOKEN     (gtoken_s){TOK_KEY_UNDEFINED,0,0,0,0,0,0,0,NULL}
```

**Comment by dxramax** [comment]
the `NULL` is causing the warning, if you change it to `0` the warning will not appears.

**Comment by marcobambini** [comment]
gtoken_s is a C struct declared as:
```c
struct gtoken_s {
	gtoken_t			type;		// enum based token type
	uint32_t			lineno;		// token line number (1-based)
	uint32_t			colno;		// token column number (0-based) at the end of the token
	uint32_t			position;	// offset of the first character of the token
	uint32_t			bytes;		// token length in bytes
	uint32_t			length;		// token length (UTF-8)
	uint32_t			fileid;		// token file id
        gbuiltin_t 			builtin;        // builtin special identifier flag
	const char			*value;		// token value (not null terminated)
};
```
so there are 8 numeric fields (set to 0) and 1 char ptr field (that must be set to NULL).
Really don't understand why Visual Studio complaints about a **bool** field that does not exists in that **struct**.
