### ISSUE TITLE
potential memory leak at gravity_parser_free

### ISSUE THREAD

**Issue by dxramax** [marcobambini/gravity#143]
at parser.c line 2572, when freeing `parser->declarations`, it should by using `node_array_free` not `marray_destroy`.

**Comment by blindfuzzy** [comment]
Gravity leaks like a sieve.

**Comment by marcobambini** [comment]
@dxramax please read the comment above that line:
```c
// parser->statements is returned from gravity_parser_run
// and must be deallocated using gnode_free
```
Gravity needs to free memory occupied by the array but not the nodes that build the AST.

**Comment by marcobambini** [comment]
I extensively tested Gravity for memory leaks, there could be some leaks in malformed source code or code that contains erroneous characters. But there are no leaks at runtime or in successfully compiled code.

**Comment by dxramax** [comment]
the comment is for `parser->statements`, is this also apply for `parser->declarations`

**Comment by marcobambini** [comment]
parser->declarations is used to keep track of nodes hierarchies and it contains pointer to parser->statements nodes so there is no need to free it using node_array_free because nodes are freed when AST is freed. I probably should write a better comment about its usage.

**Comment by dxramax** [comment]
@marcobambini thanks for the explanation.
