### ISSUE TITLE
2017-04-25 - Segmentation Faults

### ISSUE THREAD

**Issue by rwhitworth** [marcobambini/gravity#155]
Hi again,
More results from afl-fuzz and a few more crashes.  You have been making great progress on closing these and I notice others have reported (and submitted PR fixes) to help close problems out.  I'm glad to see progress.

See here for test cases: https://github.com/rwhitworth/gravity-fuzz/tree/master/2017-04-25.  I just tested these against the latest git commit and they should still be valid.

As ever, thank you for taking a look at these, and good luck debugging :-)

**Comment by blindfuzzy** [comment]
As an FYI there are no security issues in those segfaults they are merely memory leaks.

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/a58675e0a898c624d6ea3970d41224bdda88d47b.
@rwhitworth I'd like to thank you again for your help, these tests are essential in order to be able to build a solid language.

Gravity has now more than 900 unit test.
Thanks!
