### ISSUE TITLE
2017-05-04 Segmentation Faults

### ISSUE THREAD

**Issue by rwhitworth** [marcobambini/gravity#156]
See here for test cases: https://github.com/rwhitworth/gravity-fuzz/tree/master/2017-05-04. I just tested these against the latest git commit and they should still be valid.

I'm trying some new configuration options for AFL-Fuzz (setting AFL_INST_RATIO) in the hopes of finding some new code paths to increase coverage.

Thanks for looking into this

**Comment by blindfuzzy** [comment]
@rwhitworth what did you set it at?

**Comment by marcobambini** [comment]
Thanks @rwhitworth. All fixed by https://github.com/marcobambini/gravity/commit/b07ed8f76a47c93d0c64d7e940093966e8422338.

**Comment by rwhitworth** [comment]
@blindfuzzy Currently using `AFL_HARDEN=1 AFL_INST_RATIO=50 AFL_NO_BUILTIN=1`.  Based on my understanding of how AFL uses the bitmap I don't need to use that setting, but I hope that by changing it periodically it will allow different code paths to be instrumented and focused on by tests.

I don't track code coverage across runs.  Do you use something like https://github.com/mrash/afl-cov ?

**Comment by blindfuzzy** [comment]
I use that and also ./afl-whatsup, which is easier to use if I don't want to compile with gcov and all that other stuff. I set AFL_INST_RATIO=100 yesterday to check the type of coverage I was getting and nothing really changed on my end. That's why I am curious how it is working out for you. Are you fuzzing with a large corpus or just the unittest cases that come with gravity? @rwhitworth

**Comment by rwhitworth** [comment]
@blindfuzzy I started fuzzing with a file containing a single period `.` (my goto when starting a fuzzing project) and have evolved into using a subset of unit tests and using outputs that previously caused issue.  After a few more days of fuzzing the current master branch, afl-fuzz is only reaching ~6.8% code coverage.  No doubt this can be improved.

**Comment by blindfuzzy** [comment]
@rwhitworth I'm a 'hello' guy myself in that regards. I'm using about 60k test cases at this point across 32 cores with 98-99% coverage. We reused a lot from previous fuzzing and gather up all of yours to use as well along with making a bunch of our own testcases to fuzz with.
