### ISSUE TITLE
Assertion triggered in gravity_ircode.c

### ISSUE THREAD

**Issue by rwhitworth** [marcobambini/gravity#159]
```
gravity: src/compiler/gravity_ircode.c:439: void ircode_register_protect_outside_context(ircode_t *, uint32_t): Assertion `code->state[nreg]' failed.
```

The test cases all look to trigger the same assertion, and are located here: https://github.com/rwhitworth/gravity-fuzz/tree/master/2017-05-10

**Comment by marcobambini** [comment]
Thanks a lot @rwhitworth.
All fixed by https://github.com/marcobambini/gravity/commit/6eda92e1c4f9a743e15828185dcd5374c84b0175

**Comment by rwhitworth** [comment]
Thanks @marcobambini!  Verified and closing Github issue.
