### ISSUE TITLE
Is there a way to use multiple gravity files?

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#16]
Similarly with other languages where you want to keep things organized by having different functionality implemented in different files, is there a way to have multiple gravity files with different functionality, and combine them?

As an example, say one gravity file is a function that calculates the factorial of a number, and the other file contains the main function where you will call the factorial function from the other file.

Is such a thing possible?

**Comment by hallzy** [comment]
This would also be useful for testing purposes.

As an example, implementing a function in the source of a project, and calling that function in a test, in order to test that the function is correct.

Running multiple related tests in the same test file would also be useful

**Comment by marcobambini** [comment]
Yes it is possible, even if it just a preliminary implementation that needs to be extended, you can use the import statement to use more files:

import "file1.gravity"
import "file2.gravity"
...
I need to write a bit more documentation about the correct usage of the import statement.
