### ISSUE TITLE
clang: -std=gnu99 vs -std=gnu11

### ISSUE THREAD

**Issue by rwhitworth** [marcobambini/gravity#161]
When compiling with the clang compiler these warnings are shown:
```
In file included from src/compiler/gravity_symboltable.c:9:
src/compiler/gravity_symboltable.h:15:30: warning: redefinition of typedef 'symboltable_t' is a C11 feature [-Wtypedef-redefinition]
typedef struct symboltable_t    symboltable_t;
                                ^
src/compiler/gravity_ast.h:66:33: note: previous definition is here
typedef struct symboltable_t                            symboltable_t;
                                                        ^
```

They can be fixed by changing the Makefile from using `-std=gnu99` to `-std=gnu11`.  I notice that gcc does not complain about this warning.  I'm not sure what other changes come with updating the C standard, but wanted to report this in case the change makes sense to you.

**Comment by marcobambini** [comment]
Thanks @rwhitworth, I'd like to have it fixed even for C99 even if I haven't yet found a way to completely fix it.

**Comment by marcobambini** [comment]
All fixed by https://github.com/marcobambini/gravity/commit/07491e10d9ec0072c172fdcf7667ba55367a7028
