### ISSUE TITLE
Big endian?

### ISSUE THREAD

**Issue by ibara** [marcobambini/gravity#165]
How much do we care about big endian architecture support? I built gravity on OpenBSD/octeon (a mips64 CPU) and there are 240 unittest failures.

https://devio.us/~bcallah/gravity-tests-openbsd-octeon.log

I can mark the OpenBSD package to only be available on little endian architectures, but if it's simply an oversight or trivial fix, it might be better to offer it on all platforms.

**Comment by marcobambini** [comment]
I am really interested in fixing all of them, should be a trivial fix.
Can you give me more details?

**Comment by ibara** [comment]
Sure. What details do you need?

**Comment by marcobambini** [comment]
Just try to execute a test that fails and print the exact error message.
Thanks.

**Comment by marcobambini** [comment]
Hi @ibara any news about the test?

**Comment by ibara** [comment]
Hi, sorry I've been very busy lately but this is on my list of things to do!

**Comment by ibara** [comment]
I'll be getting back to this soon!

**Comment by marcobambini** [comment]
Thanks @ibara!

**Comment by ibara** [comment]
Hi. Here is the output of:
```
736     Test file: loop1.gravity
        Test path: test/infiniteloop/loop1.gravity 
        SYNTAX ERROR on 0 (2,9): Expected literal expression but found ERROR.
        FAILURE
```
which is the first test that fails.
Running the file itself yields this output:
```
$ uname -a
OpenBSD mips.anthrobsd.net 6.1 GENERIC#0 octeon
$ gravity --version
Gravity version 0.2.8 (Jul  9 2017)
$ gravity loop1.gravity                                                                                                                         
SYNTAX ERROR on 0 (2,9): Expected literal expression but found ERROR.
SYNTAX ERROR on 0 (21,25): Expected } but found EOF.
$
```

**Comment by marcobambini** [comment]
Hi @ibara is there a way to have a temporary ssh access to that computer?

**Comment by ibara** [comment]
So that machine is my border gateway. But I can set up another big endian machine (an iMac G4) running OpenBSD/macppc sometime this weekend and give you access to that.

**Comment by marcobambini** [comment]
That would be extremely useful @ibara, thanks a lot!

**Comment by ibara** [comment]
Hi.
Please send me an email at <bcallah AT openbsd DOT org> with a user name and an ssh public key so I can set you up on that macppc machine.

**Comment by marcobambini** [comment]
Thank you very much @ibara.
Issue has been fixed by https://github.com/marcobambini/gravity/commit/02dc0af07eb7c08ca7644c29e9aaa779ee591da9.
