### ISSUE TITLE
Help package maintainers

### ISSUE THREAD

**Issue by ibara** [marcobambini/gravity#169]
Hi --

I just imported gravity into the official OpenBSD packages repository: http://marc.info/?l=openbsd-ports-cvs&m=149758420809464&w=2
Now OpenBSD users can simply type `pkg_add gravity` and get right to using it. Neat!

I have one request though, which would make my life much easier (as well as any other package maintainers who might come around here): whenever you raise the version number in `src/shared/gravity_value.h`, could you also make a GitHub tag of that commit? It doesn't have to be a full release. Our system of tracking out-of-date packages knows how to talk to GitHub, and a new tag will send me a message letting me know it's time to update gravity in the package system.

Thanks!

**Comment by marcobambini** [comment]
Hi @ibara thanks a lot!
I'll add a note to the official wiki page.

I'll tag the commit starting from the next version number raise.
Thanks!
