### ISSUE TITLE
BUG !

### ISSUE THREAD

**Issue by qs9816** [marcobambini/gravity#171]
`func main() {
 for (var i in 0...10000000) {
    Int.random(1, 10);
 }
 System.print("ok !");
}
`

RUNTIME ERROR: Infinite loop detected. Current execution must be aborted.

**Comment by marcobambini** [comment]
Thanks a lot @qs9816!
Issue has been fixed by https://github.com/marcobambini/gravity/commit/8c7159e1d84d5f83a8c37e60eb183d60f0f268e2
