### ISSUE TITLE
Command Feature (similar to python -c ...)

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#173]
Something like the `python -c` feature would be handy sometimes...

ie:

```python
python -c 'print "A" * 10'`
```

Would be a one line command to print `A` 10 times. Essentially, being able to write a gravity script at the terminal to work with other bash commands without the need for actually writing a gravity file.

**Comment by marcobambini** [comment]
Hello @hallzy,
just added the -i option (immediate) to implement that feature:
`gravity -i "return 10+20;"`
https://github.com/marcobambini/gravity/commit/98e4919322d04a2110139e444711f5838f66eae4
