### ISSUE TITLE
gravity_optimizer.c:388 NULL pointer dereference

### ISSUE THREAD

**Issue by rwhitworth** [marcobambini/gravity#175]
`if (IS_NUM(inst1)) flag = optimize_const_instruction(inst, inst1, NULL);`

It looks like this line of code causes a NULL pointer dereference in function `optimize_const_instruction` line 276:
`if (inst1->tag == inst2->tag) type = inst1->tag;`

I would offer a PR, but I'm uncertain how gravity should handle this case.  Also, my C is rusty (non-existent?)  so I may be misunderstanding how inst2 is being handled.

**Comment by marcobambini** [comment]
You are right, there is a condition that can cause a NULL pointer dereference.
I am looking to fix it.
Thanks!

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/51eb59d927a8eae1ff0ec0cc06c76f99c6466b3b
