### ISSUE TITLE
Having an issue with the new Math class

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#177]
It seems that all the math methods aren't working for me.

As an example:

```swift
#!/bin/gravity

func main() {
  return Math.pow(10,2)
}
```

I would expect this to return "100", but it returns "undefined" instead:

```
$ ./math.gr 
RESULT: UNDEFINED (in 0.0048 ms)
```

I have looked at the code and nothing jumps out at me as to why this would be the case.

The constants seem to work though so that seems okay.

And the Math.random() method always returns 0, although, if you cast "r" to a float that seems to fix that one, since otherwise it is an integer division.

```c
RETURN_VALUE(VALUE_FROM_FLOAT((float)r / RAND_MAX), rindex);
```

**Comment by marcobambini** [comment]
All fixed by https://github.com/marcobambini/gravity/commit/f44a6f06b32d8a39ae3bd6e7fb126e55c5378c63
