### ISSUE TITLE
Issue with new sort()

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#188]
So, my understanding of sorting with a predicate is minimal, but from what I do understand, a predicate function will return a boolean value, and based on the evaluation the sort function will sort in the data in a specific way.

When I try both of these examples, I get a segmentation fault:

```swift
func main() {
  func x(a, b) { return a <= b }

  var list = [1,2,3,4,5,6,7]
  list.sort(x);
  return list.String()
}
```

```swift
func main() {
  func x(a, b) { return a < b }

  var list = [1,2,3,4,5,6,7]
  list.sort(x);
  return list.String()
}
```

Also while I am here, I wouldn't mind an explanation of how one would actually create a predicate function to do something interesting.

So for example, if I want to sort a list so that the list is in numeric order, but all even numbers come before odd numbers. Would such a thing be possible?

**Comment by hallzy** [comment]
Also, the problem I am having with the seg fault could be because, in the first execution of quicksort() partition returns 0 for pi, but then pi-1 is passed into quicksort, and since pi is an unsigned integer when quicksort is called, high now becomes 4294967295. When you enter partition() with that value it tries to access an array element that doesn't exist.

**Comment by marcobambini** [comment]
Thanks @hallzy seems like more testing is needed (I cannot test the code today).

**Comment by MatanSilver** [comment]
Thanks @hallzy it seems this slipped through the unit test, which must have been a functioning edge case! I'll try to fix it today...

**Comment by MatanSilver** [comment]
And as a response to your question @hallzy :

> Also while I am here, I wouldn't mind an explanation of how one would actually create a predicate function to do something interesting.
> So for example, if I want to sort a list so that the list is in numeric order, but all even numbers come before odd numbers. Would such a thing be possible?

I'm no expert by any means but it seems to me that changing the predicate behavior to cause sorting in a different fashion is _possible_ but the behavior is hard to get right. A multi-tiered sort (i.e. even/odd, then increasing in value), is a bit easier to implement, since you can treat the different tiers as an "order of operations" of sorts for the sort. Here's an interesting example, following the behavior you thought of:

```
func main() {
  func predicate(a,b) {
    if ((a % 2 == 0) && (b % 2 == 0)) {
      return a > b
    } else if (a % 2 == 0) {
      return false
    } else if (b % 2 == 0) {
      return true
    } else {
      return a > b
    }
  }
  System.print([1, 2, 3, 4, 5, 6, 7].sort(predicate))
  System.print([1, 6, 4, 5, 3, 8, 9, 7, 11].sort(predicate))
}
```

This gives the following result:
```
[2,4,6,1,3,5,7]
[4,6,8,1,3,5,7,9,11]
RESULT: NULL (in 0.1249 ms)
```

**Comment by marcobambini** [comment]
@hallzy can you please confirm that the issues are fixed by https://github.com/marcobambini/gravity/commit/e2ddf359b2f29a274353652108427746de12b522?

**Comment by hallzy** [comment]
@MatanSilver thanks :) your changes seem to have fixed the problems I was having.

As for the example you gave, I still find it somewhat confusing. Maybe I will just have to look harder to see if there is an expert on the internet on this sort of thing. I tried to look a bit before but came up empty... most of what I found was explaining how predicates work for a filter() function, but that (at least for me) is much easier to understand.

**Comment by hallzy** [comment]
speaking of the filter() I mentioned above, I just realized that I don't think gravity has one

**Comment by MatanSilver** [comment]
Yeah I noticed the lack of filter too, as well as map and reduce. Not sure if those are all things that we want but they are all sort of in the same family of standard list operations, I suppose. 

So my idea behind that example was that the first layer of comparison, so to speak, only checks for if one item is even and the other is odd. If that is the case, the boolean return is only dependent on which is even and which is odd (if they need to be flipped to opposite sides of the list or not). If the sort function comes across two values and they are either both even or both odd, it has to return a value that reflects which is bigger (i.e. a > b). It seemed like a good idea but evidently there were some lists I tried that didn't work and had even numbers on the wrong side, though my first tests did get close.

**Comment by marcobambini** [comment]
@hallzy @MatanSilver what are you looking for can be found at https://github.com/parro-it/gravity-func

**Comment by hallzy** [comment]
Interesting. I was looking for native methods.

Perhaps I should open a new issue for this but I am having quite a few issues with these new functions as well. If I use that map() as an example, and use a list with 9 or more items I get problems... namely, if I use those functions in the repo you mentioned and then I do:

```swift
func double(x) {
  return x * 2
}

func main() {
  var list = [1,2,3,4,5,6,7,8,9]
  return map(double, list)
}
```

I get 

```
RESULT: (LIST) [2,4,6,8,10,12,14,16,18] (0xe804f0) (in 0.0258 ms)

*** Error in `/bin/gravity': double free or corruption (!prev): 0x0000000000e80190 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f4ba38ad7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f4ba38b637a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f4ba38ba53c]
/bin/gravity[0x435f32]
/bin/gravity[0x41836f]
/bin/gravity[0x421fb7]
/bin/gravity[0x401b6d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f4ba3856830]
/bin/gravity[0x401eb9]
======= Memory map: ========
00400000-0044e000 r-xp 00000000 08:02 8388923                            path/to/gravity/gravity
0064e000-0064f000 r--p 0004e000 08:02 8388923                            path/to/gravity/gravity
0064f000-00650000 rw-p 0004f000 08:02 8388923                            path/to/gravity/gravity
00650000-00651000 rw-p 00000000 00:00 0 
00e50000-00e92000 rw-p 00000000 00:00 0                                  [heap]
7f4b9c000000-7f4b9c021000 rw-p 00000000 00:00 0 
7f4b9c021000-7f4ba0000000 ---p 00000000 00:00 0 
7f4ba3403000-7f4ba3419000 r-xp 00000000 08:02 18878854                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4ba3419000-7f4ba3618000 ---p 00016000 08:02 18878854                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4ba3618000-7f4ba3619000 rw-p 00015000 08:02 18878854                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4ba3619000-7f4ba3631000 r-xp 00000000 08:02 18874865                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4ba3631000-7f4ba3830000 ---p 00018000 08:02 18874865                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4ba3830000-7f4ba3831000 r--p 00017000 08:02 18874865                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4ba3831000-7f4ba3832000 rw-p 00018000 08:02 18874865                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4ba3832000-7f4ba3836000 rw-p 00000000 00:00 0 
7f4ba3836000-7f4ba39f6000 r-xp 00000000 08:02 18875655                   /lib/x86_64-linux-gnu/libc-2.23.so
7f4ba39f6000-7f4ba3bf6000 ---p 001c0000 08:02 18875655                   /lib/x86_64-linux-gnu/libc-2.23.so
7f4ba3bf6000-7f4ba3bfa000 r--p 001c0000 08:02 18875655                   /lib/x86_64-linux-gnu/libc-2.23.so
7f4ba3bfa000-7f4ba3bfc000 rw-p 001c4000 08:02 18875655                   /lib/x86_64-linux-gnu/libc-2.23.so
7f4ba3bfc000-7f4ba3c00000 rw-p 00000000 00:00 0 
7f4ba3c00000-7f4ba3c07000 r-xp 00000000 08:02 18874873                   /lib/x86_64-linux-gnu/librt-2.23.so
7f4ba3c07000-7f4ba3e06000 ---p 00007000 08:02 18874873                   /lib/x86_64-linux-gnu/librt-2.23.so
7f4ba3e06000-7f4ba3e07000 r--p 00006000 08:02 18874873                   /lib/x86_64-linux-gnu/librt-2.23.so
7f4ba3e07000-7f4ba3e08000 rw-p 00007000 08:02 18874873                   /lib/x86_64-linux-gnu/librt-2.23.so
7f4ba3e08000-7f4ba3f10000 r-xp 00000000 08:02 18875432                   /lib/x86_64-linux-gnu/libm-2.23.so
7f4ba3f10000-7f4ba410f000 ---p 00108000 08:02 18875432                   /lib/x86_64-linux-gnu/libm-2.23.so
7f4ba410f000-7f4ba4110000 r--p 00107000 08:02 18875432                   /lib/x86_64-linux-gnu/libm-2.23.so
7f4ba4110000-7f4ba4111000 rw-p 00108000 08:02 18875432                   /lib/x86_64-linux-gnu/libm-2.23.so
7f4ba4111000-7f4ba4137000 r-xp 00000000 08:02 18874415                   /lib/x86_64-linux-gnu/ld-2.23.so
7f4ba4308000-7f4ba430c000 rw-p 00000000 00:00 0 
7f4ba4333000-7f4ba4336000 rw-p 00000000 00:00 0 
7f4ba4336000-7f4ba4337000 r--p 00025000 08:02 18874415                   /lib/x86_64-linux-gnu/ld-2.23.so
7f4ba4337000-7f4ba4338000 rw-p 00026000 08:02 18874415                   /lib/x86_64-linux-gnu/ld-2.23.so
7f4ba4338000-7f4ba4339000 rw-p 00000000 00:00 0 
7ffe4cfa1000-7ffe4cfc2000 rw-p 00000000 00:00 0                          [stack]
7ffe4cfe6000-7ffe4cfe8000 r--p 00000000 00:00 0                          [vvar]
7ffe4cfe8000-7ffe4cfea000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted
```

if however I write my own map function as a method of a class

```swift
class MyList {
  var list = []
  func init() {
    list = _args
  }
  func map(fn) {
    var tmp = []
    list.loop(func(val) {
      tmp.push(fn(val))
    })
    list = tmp
    return list
  }
}

func main() {
  var mylist = MyList(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
  return mylist.map(double).String()
}
```

I get this output (which is better, but actually has a mathematical error)

```
RESULT: (STRING) [2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36.380000,40] (0x11a1e80) (in 0.0551 ms)
```

Weirdly, the 36 and the 38 are there, but they have been stuck into one number and are now `36.38` instead of `36,38`

**Comment by marcobambini** [comment]
Seems like a good time to natively introduce map, filter and reduce methods to both List ad Map types.
@hallzy the double free/corruption issue seems like a Gravity bug I should fix.

**Comment by marcobambini** [comment]
@hallzy issue fixed by https://github.com/marcobambini/gravity/commit/fa26077135ea9102195980a9ae3fc2ec686f84ba

**Comment by MatanSilver** [comment]
I might be interested in implementing native map, filter, and reduce methods if nobody else gets to it first (I'm quite busy at the moment). Should that be a separate issue?

**Comment by marcobambini** [comment]
Hi @MatanSilver, yes a separate issue would be recommended.
As a reference: [https://useyourloaf.com/blog/swift-guide-to-map-filter-reduce/](https://useyourloaf.com/blog/swift-guide-to-map-filter-reduce/)
Thanks!
