### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by nixfox** [marcobambini/gravity#19]
There seems to be no contribution guide for people that would love to help with your project.

**Comment by marcobambini** [comment]
I'd love to add it!
Doesn't the text in ReadMe work?
Is there a better way?

**Comment by nixfox** [comment]
Well I mean, it tells us the obvious, on problems file an issue and if you wish to contribute create a pull request.

What I am personally missing is contributing guidelines which should tell the people:
- Code style and syntax rules
- Where to make changes
- What changes would be welcome or are already planned
- Code review rules
- Testing rules

**Comment by Dohxis** [comment]
Would love to contribute myself so better guide how to is essential.

**Comment by marcobambini** [comment]
Hi guys, I just added a CONTRIBUTING.md file.
Feel free to add more information to it.
