### ISSUE TITLE
Potential error in marray_resize()

### ISSUE THREAD

**Issue by MatanSilver** [marcobambini/gravity#195]
In gravity_array.h, marray_resize() is defined as:
```
#define marray_resize(type, v, n)	(v).m += n; (v).p = (type*)realloc((v).p, sizeof(type) * (v).m)
```
I believe this has a bug--when resizing, it is v.n (the struct member that stores the total allocated size), not v.m (the struct member that stores the maximum index of the last element set) that should be incremented by the macro argument n. This macro hasn't been used in the codebase as far as I can tell.

**Comment by marcobambini** [comment]
@MatanSilver thanks for your feedback.
marray_resize is widely used in the codebase (gravity_hash.c, gravity_value.c and gravity_core.c). Resize means resize the internal memory (and not the number of items that the array contains) so I think the macro is right. It should probably be renamed marray_realloc, the resize suffix is a bit misleading.
