### ISSUE TITLE
Suggestion: For windows mingw-make, add CC variable in Makefile

### ISSUE THREAD

**Issue by shawnye** [marcobambini/gravity#198]
Without `CC=gcc` in Makefile, error occurs when do `mingw-make`:

<pre>
process_begin: CreateProcess(NULL, cc...)failed. 
make (e=2):
</pre>

**Comment by marcobambini** [comment]
Thanks @shawnye.
Fixed by https://github.com/marcobambini/gravity/commit/b9f36f6a8a88e8cff383f45e36c31779271cb58b
