### ISSUE TITLE
Suggestion: add some useful functions and more

### ISSUE THREAD

**Issue by shawnye** [marcobambini/gravity#199]
First of all, I like gravity syntax very much, I want to build tools using gravity !

But the drawback is obviously , it is less of functions and I do not  want  embeding gravity, I just want to use gravity  like lua with lot of libs ,whatever writing use gravity or binding c lib. (Forgive my poor English)

Before the standard lib being growed mature, I wish gravity can provide some nesesary functions( in my view), then I could build some tools on them , thanks!  

- string.trim()
- string.starts_with() or like
- string.ends_with()
- io: file,open().read(), write(), delete(), stat() , mkdir() and so on 
- system.exec() ,system.evironment(), system.read() or like

**Comment by shawnye** [comment]
I see gravity_utils.h contains a lot of useful function ,how to use it ?

**Comment by marcobambini** [comment]
Thanks @shawnye for the post.
We'll add more functions in the future thanks also to our invaluable contributors.

**Comment by marcobambini** [comment]
In order to use the functions inside gravity_utils.h just add gravity_utils.c and gravity_utils.h to your C/C++ project and call the functions you need.

**Comment by shawnye** [comment]
Thank you!

For use of `gravity_utils.h`, in fact I mean how to use them  in gravity script . (Again forgive my poor English)
At last I found `gravity_utils.h` is just for internal use right now ,  not for script use.
