### ISSUE TITLE
Community chat

### ISSUE THREAD

**Issue by Dohxis** [marcobambini/gravity#20]
Hello, I think it is a good idea to make a group chat for people to discuss about Gravity. For example Slack chat would let this small community grow faster.

**Comment by marcobambini** [comment]
That's a very good idea.
I just created it: https://gravity-lang.slack.com/

**Comment by Dohxis** [comment]
You need to create automation app for invites. For example https://github.com/outsideris/slack-invite-automation

**Comment by Dohxis** [comment]
@marcobambini you need to create automation app for invites. For example https://github.com/outsideris/slack-invite-automation

**Comment by WorksOfBarry** [comment]
It may be an option to use Gitter, instead. Either is good!

**Comment by Dohxis** [comment]
Yes, but if Slack is already created hosting invitation app is couple of clicks.

**Comment by kazzkiq** [comment]
Looking forward for this. Gitter also seems a better alternative for a public chat, in my opinion (no need for invitation, direct repo integration, github accounts, etc).

**Comment by marcobambini** [comment]
Hi guys I opened a Gitter community for Gravity, it seems better than Slack for GitHub projects: https://gitter.im/gravity-lang/Lobby
