### ISSUE TITLE
Benchmark required

### ISSUE THREAD

**Issue by yangrq** [marcobambini/gravity#201]
I am very interested in the performance of the gravity-lang.Is there a benchmark (comparing to lua, luajit, wren and etc.)?

**Comment by marcobambini** [comment]
@yangrq Gravity should be pretty fast and some third-party dev made some performance test some time ago, however we don't have an official benchmark test suite. Could you be interested in developing one?

**Comment by yangrq** [comment]
Thanks for your reply. I will try when available (I'm so busy!) :)
