### ISSUE TITLE
Number multiply by string

### ISSUE THREAD

**Issue by agusbena** [marcobambini/gravity#207]
this code:

```
var a = 10;
System.print("Bad computation: " + (a * "hi"));

```
will output:

`Bad computation: 0`

Which is scary, at least it should ouput NaN or throw exception or something.

**Comment by marcobambini** [comment]
"hi" is converted to number, resulting in 0. So 10 * 0 = 0

**Comment by agusbena** [comment]
But converting a "hi" string to 0 this is conceptually wrong, and can lead to a hard to track bugs.

I am no trying to be academic here, I just point out again that this might be really hard problem to solve, And we can not trust in a language that can potentially deliver computational wrong result to users using system build with Gravity, It at least should fail, crash or something but not lie on the result.

This needs to be fixed. Or at, least please elaborate:

1) Why in the heaven this is allowed?
2) If 1) will be maintained,  How can I validate arithmetic operations if for mistake i use a different data type than number.

Thanks

**Comment by marcobambini** [comment]
That's the reason why we introduced the is operator:
```
var b = "3.14"
var c  = b * 2.0;
if(c is Float) {
    //its float like i intended.
}
```

null is the default value for variables:
```
var a = 10;
var b; // default to null
return a * b; // 0 is returned in this case 
```

**Comment by marcobambini** [comment]
It turns out that it is a bit more complicated than that.
I implemented the extra check and everything worked as expected, except for a code like:

```
class Rect {
	var x,y,w,h;
	
	func init (n1,n2,n3,n4) {
		x = n1;
		y = n2;
		w = n3;
		h = n4;
	}
	
	func Int() {
		return x+y+w+h;
	}
}

func main() {
	var a = 10;
	var b = Rect(100,200,300,400);
	return a + b;
}
```

Please note that the Rect class declares a Int method which is automatically used when an instance needs to be converted to an Int. The same is true for Strings. So probably the **is** check is the right way to proceed.

**Comment by marcobambini** [comment]
@agusbena my proposal is to remove automatic String to Number conversion but if a class implements the Int function then it is perfectly legal to perform a math operation between a number and that class.

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/7918f1407f4bf42843a69ab575573a7503ea63f6
