### ISSUE TITLE
building with Visual Studio

### ISSUE THREAD

**Issue by matkuki** [marcobambini/gravity#209]
Hi,

I tried compiling the Visual Studio project, but got a lot of *missing header file* errors.
So I added the *src/compiler*, *src/optionals*, *src/runtime*, *src/shared*, *src/utils* and changed *#include <strings.h> -> #include <string.h>* in *gravity_memory.h* and these errors go away, but then I get:
```
Macro definition of snprintf conflicts with Standard Library function declaration
```
in the *gravity_memory.h* file.

A little help please?

**Comment by marcobambini** [comment]
Which Visual Studio version are you using?

**Comment by matkuki** [comment]
Windows 10
Visual Studio 2017
Windows SDK Version 10.0.15063.0

**Comment by marcobambini** [comment]
Hi @matkuki I made several improvements with https://github.com/marcobambini/gravity/commit/c9f599abb3cea0b496f73782adc9262594a793bf.

I was only able to generate the DLL, can you please take a look at the project and modify it in order to be able to generate gravity.exe and unittest.exe files too?

**Comment by matkuki** [comment]
Hey @marcobambini ,

Just made a fresh clone of the repository, tried compiling without changing anything and got the output, show in the attached text file:
[error_output.txt](https://github.com/marcobambini/gravity/files/1859683/error_output.txt)

Hope it helps. If you need me to try anything, let me know.

**Comment by matkuki** [comment]
Played around a little bit and changed line **71** in **gravity_json.h** to:
```c++
#ifndef json_int_t
   #ifndef _MSC_VER
      #define json_int_t int64_t
   #else
      #define json_int_t __int64
      //#define snprintf   _snprintf // <--- COMMENTED THIS OUT
   #endif
#endif
```
and now it compiles to a **.dll**.

Will play around a little more to get the **.exe** application and tests as you mentioned.

**Comment by marcobambini** [comment]
@matkuki thanks ... what sounds strange to me if that the same exact code compiles and runs fine on Visual Studio Express 2013 (Windows 7 Pro).
