### ISSUE TITLE
Input from stdin?

### ISSUE THREAD

**Issue by jkleiser** [marcobambini/gravity#21]
Does the System class have methods for reading from stdin?
I can see no mention of it here: https://marcobambini.github.io/gravity/system.html

**Comment by marcobambini** [comment]
Not yet, I'll probably add it as soon as I'll setup a REPL mode.

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/f67c05b18c14778ee17853430dfe6774dc98e33b
