### ISSUE TITLE
Bound Closures Bug

### ISSUE THREAD

**Issue by AlaaAlHallaq** [marcobambini/gravity#211]
In c# an instance method has a target that will be the 'this' reference for the inner code.
In gravity I can get the reference of an instance method , e.g.:
`var strRepeate = "textvalue".repeat`
but calling the closure `strRepeate` would result in an undetermined behavior because the target for the method repeat is not stored in the strRepeate variable.

I came to this conclusion by debugging the c code of the method string_repeat which have the `arg[0]` of undefined value.

So is it intended by Gravity to get the reference of an instance method if not this undefined behavior should be resolved.

the same could be applied on static methods, e.g.: `var compute_sin = Math.sin`, but since the `arg[0]` for a static method is the meta class, and it would be rarely used, even if it is undefined using this way.

**Comment by marcobambini** [comment]
You are right, there is an issue in this specific case.
Do you have a suggestion for a possible fix?

**Comment by AlaaAlHallaq** [comment]
👍👍👍👍👍👍👍👍👍👍👍

**Comment by AlaaAlHallaq** [comment]
is this bug also supports binding class functions (static functions) ?

**Comment by marcobambini** [comment]
`bound_bar.bind(Foo)`

**Comment by AlaaAlHallaq** [comment]
ok thats solves the problem, but should not the static function be bound to the meta class by default and the instance functions bound to the instance of the class.
