### ISSUE TITLE
Gravity Struct vs Gravity Class

### ISSUE THREAD

**Issue by AlaaAlHallaq** [marcobambini/gravity#215]
As a C , C++ and C# developer:
* a struct is a collection of variables passed by value: the struct fields values (for fields of pointer types [or in managed languages (fields of pointer objects types)] the references) Copied every time a struct instance is assigned to another variable.

* and for a class instance the reference of that instance is copied to the newly assigned variable.

for the following code should not `bstr.a` value be `"text"` instead of `"newStr"` :

`struct Strc { var a }`
`func main(){`
`	var str = Strc()`
`	str.a = "text"`
`	var bstr = str;`
`	str.a = "newStr"`
`	System.print(str.a)`
`	System.print(bstr.a) //prints "newStr"`
`}`

so the main question what is the purpose of "struct" key word in GravityLang.

**Comment by marcobambini** [comment]
Struct is parsed but not implemented in any way. I reserved the struct keyword for future support (a struct is now an alias to class),
