### ISSUE TITLE
Hello World program?

### ISSUE THREAD

**Issue by wolframroesler** [marcobambini/gravity#219]
Hi,

is there a simple Hello World program in Gravity? I didn't find one in the docs.

Asking because I'm the maintainer of the Hello World Collection (http://helloworldcollection.de/) to which I'd like to add a Gravity program.

Thanks!

**Comment by marcobambini** [comment]
Hi @wolframroesler and thanks for contacting me, I really need to update the Getting Started section.

Hello World in Gravity looks like:
```swift
func main() {
    System.print("Hello World!");
}

**Comment by wolframroesler** [comment]
Thanks, it's online in the Hello World Collection now.

http://helloworldcollection.de/#Gravity
