### ISSUE TITLE
arm target?

### ISSUE THREAD

**Issue by bwanaaa** [marcobambini/gravity#223]
has the src been compiled for a raspberry pi?

**Comment by marcobambini** [comment]
The source has already be compiled for ARM targets (and tested for both little/big endian processors).
You should be able to compile it yourself just installing gcc and make on your raspberry pi.

**Comment by marcobambini** [comment]
You should be able to get it up and running using the commands:
```
git clone https://github.com/marcobambini/gravity.git
cd gravity
make
```
