### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by chrisfinazzo** [marcobambini/gravity#225]
With your permission, I'd like to package this for Homebrew. The current WIP is below, any help you can provide is appreciated. Unfortunatly, I'm not familiar enough with C to know specifics re the install procedures or how this should be tested.

    class Gravity < Formula
      desc "The Gravity Programming Language"
      homepage "http://gravity-lang.org"
      url "https://github.com/marcobambini/gravity/archive/0.5.0.tar.gz"
      sha256 "ac05e5d154eac5c8159f4142b667b32021b4e4b7869ff993cf5eb7258fbfe85c"
      depends_on "cmake" => :build
    
      def install
        system "make", "install"
      end
    
      test do
    
        system "false"
      end
    end

**Comment by marcobambini** [comment]
Hi @chrisfinazzo I am really interested in getting Homebrew support for Gravity. Let me better check the requirements.

**Comment by IngwiePhoenix** [comment]
Hello @chrisfinazzo !

Now, I am the other way around - I have no idea how to write a Homebrew formula - so allow me to help you out. :)

- Make Homebrew build from source, if possible. There aren't binaries for OS X, but tagged commits.
- Basically, all that needs to be done is this: `mkdir build && cd build && cmake .. && make && make install`.

If you have further questions, feel free to ask :)

**Comment by vladimyr** [comment]
Let's make it happen https://github.com/Homebrew/homebrew-core/pull/55807 🎉

**Comment by vladimyr** [comment]
Successfully done! Btw @marcobambini if you have a moment to quickly list which sources/headers are required when linking against libgravity I could update the formula to add them together with built lib.

**Comment by marcobambini** [comment]
Thank you so much @vladimyr!!! It is really nice to be part of Homebrew :-)

**Comment by marcobambini** [comment]
For the libgravity here you go the full list:
- gravity_ast.c
- gravity_codegen.c
- gravity_compiler.c
- gravity_ircode.c
- gravity_lexer.c
- gravity_optimizer.c
- gravity_parser.c
- gravity_semacheck1.c
- gravity_semacheck2.c
- gravity_symboltable.c
- gravity_token.c
- gravity_visitor.c
- gravity_core.c
- gravity_vm.c
- gravity_hash.c
- gravity_memory.c
- gravity_value.c
- gravity_debug.c
- gravity_json.c
- gravity_utils.c
- gravity_opt_env.c
- gravity_opt_json.c
- gravity_opt_math.c

In folders:
- src/compiler/
- src/runtime/
- src/shared/
- src/utils/
- src/optionals/

**Comment by vladimyr** [comment]
> For the libgravity here you go the full list: ...

So all of these files are required just to _talk_ to `libgravity`? 😕

In case I wasn't clear enough I'm not talking about what is needed to build it but just the headers one needs to include in a project using prebuilt `libgravity.so` or `libgravity.dylib`.
