### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [marcobambini/gravity#226]
Would you like to add more error handling for return values from functions like the following?
- [mem_alloc](https://github.com/marcobambini/gravity/blob/c9f599abb3cea0b496f73782adc9262594a793bf/src/shared/gravity_memory.h#L25 "Memory allocation") ⇒ [ircode_create](https://github.com/marcobambini/gravity/blob/207ca454e6f9804ddd5eddf554d9baef8a3b43a1/src/compiler/gravity_ircode.c#L35)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [print_version](https://github.com/marcobambini/gravity/blob/c3c652dbf273fe24784908479d48b2f1c17b58fd/src/cli/gravity.c#L78)

**Comment by marcobambini** [comment]
I should surely add a check for mem_alloc return value in ircode_create but I don't think I'll add a check for printf. I'll fix my copy right now and I'll push changes in the next days. Thanks.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by marcobambini** [comment]
Honestly speaking no, it would add too much complexity and verbosity.
I would fix every possible crash situation but in the remote possibility that printf fails I would just ignore it.

**Comment by elfring** [comment]
Development tools are available to reduce corresponding complexity concerns.
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* Would you like to [choose an other program exit status](https://en.wikipedia.org/wiki/Exit_status "Description for exit code")?
