### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [marcobambini/gravity#227]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [marray_destroy](https://github.com/marcobambini/gravity/blob/aba48153e114df05be22431c17181da925e75de2/src/shared/gravity_array.h#L20 "marray_destroy macro")
- [memdebug_init](https://github.com/marcobambini/gravity/blob/aba48153e114df05be22431c17181da925e75de2/src/shared/gravity_memory.c#L104 "memdebug_init function")

**Comment by marcobambini** [comment]
Thanks @elfring for pointing out the optimisation!
Extra checks will be removed.
