### ISSUE TITLE
ide or editor support

### ISSUE THREAD

**Issue by wangtxxl** [marcobambini/gravity#23]
this project is very good  china people need it  ！！There is a market in China  ，keep it light optimization speed

**Comment by darthdeus** [comment]
Having a syntax file for VIM would definitely be a good start :)

**Comment by hallzy** [comment]
For anyone looking for vim syntax highlighting:

Note that the PR referenced above was reverted. The URL for the vim gravity syntax can be found in the [wiki](https://github.com/marcobambini/gravity/wiki). So far it is essentially a swift syntax highlighter, but I welcome changes and additions.
