### ISSUE TITLE
Package for MacPorts

### ISSUE THREAD

**Issue by l2dy** [marcobambini/gravity#231]
Hi, I've written a [MacPorts](https://www.macports.org/) port for gravity. I renamed `unittest` to `gravity_unittest` following [a convention observed from Debian packages](https://packages.debian.org/search?searchon=contents&keywords=unittest&mode=path&suite=stable&arch=any) (`eric6_unittest` and `tlsh_unittest`). What's your opinion on the name of `unittest`?

```
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

PortSystem          1.0
PortGroup           github 1.0

github.setup        marcobambini gravity 0.5.0
categories          lang
platforms           darwin
license             MIT
maintainers         {l2dy @l2dy} openmaintainer
description         Gravity Programming Language
long_description    Gravity is a powerful, dynamically typed, lightweight, \
                    embeddable programming language written in C without any \
                    external dependencies.
homepage            https://marcobambini.github.io/gravity

checksums           rmd160  dac14af5802c731011048ee88015d2fc812ff0cf \
                    sha256  492332b70b1454511c1243b34b418e0fbfab2b6bd8c9232d45451c7939b9be8e \
                    size    896963

use_configure       no
build.args-append   CC=${configure.cc}

destroot {
    move ${worksrcpath}/unittest ${worksrcpath}/gravity_unittest
    xinstall -m 755 -W ${worksrcpath} gravity gravity_unittest \
        ${destroot}${prefix}/bin

    xinstall -m 755 -d ${destroot}${prefix}/share/doc/${name}
    xinstall -m 644 -W ${worksrcpath} README.md LICENSE \
        ${destroot}${prefix}/share/doc/${name}
}
```

**Comment by ibara** [comment]
Does MacPorts have a policy of shipping non-standalone unittest binaries in their packages? On OpenBSD, I don't include the unittest binary in our package, because it is useless without the gravity source code.

**Comment by marcobambini** [comment]
I really like to have support for MacPorts. Please wait a couple of days, I already modified gravity executable and it now can be invoked with the -t parameter in order to acts like the unittest app. In the my next push I'll remove the unittest separate executable.

**Comment by l2dy** [comment]
> it is useless without the gravity source code.

@ibara I think you misunderstood what `unittest` is. It's not used to test Gravity itself, instead it runs user-provided test files. See https://marcobambini.github.io/gravity/#/quickstart?id=unit-tests and https://marcobambini.github.io/gravity/#/unittest.

> it now can be invoked with the -t parameter

Thanks, this looks better to me.

**Comment by ibara** [comment]
@l2dy No, I understood it perfectly. It's just outside our packaging policy.

**Comment by l2dy** [comment]
@ibara OK, I get it now. AFAIK, MacPorts don't have a policy for this. Testing is part of the language in Gravity like Rust, so I think the functionality of `unittest` is important for the package.

**Comment by marcobambini** [comment]
@l2dy I removed the separate unittest tool. It has been replaced by gravity -t option. This should simplify the installation/convention process with MacPorts. Thanks for the MacPorts package!

**Comment by l2dy** [comment]
@marcobambini Thanks. Please also tag a new release with this change.

**Comment by l2dy** [comment]
Done in https://github.com/macports/macports-ports/commit/9bc2412780130595e2b93a1e98badca4123fb7bb. Feel free to submit pull requests when you tag new releases. 😉

**Comment by marcobambini** [comment]
Thanks @l2dy!
