### ISSUE TITLE
[feature request] Command line arguments

### ISSUE THREAD

**Issue by michal037** [marcobambini/gravity#235]
Hello!

What do you think to add command line arguments to the interpreter?

```gravity
./gravity myfile.gravity arg1 arg2 arg3
```
And perhaps a class or variable for read it.

**Comment by windyflying** [comment]
It's cool

**Comment by IngwiePhoenix** [comment]
The CLI program may simply pass `argv`/`argc` to the main function. Take this concept code for example:

```c
gravity_list_t *list = gravity_list_new(vm, argc);
for(int i=0; i<argc; i++) marray_push(gravity_value_t, VALUE_FROM_STRING(argv[i]), list->array);

uint32_t nparams = 1;
gravity_value_t params[] = { VALUE_FROM_LIST(list) };

gravity_value_t main_fn = gravity_vm_getvalue(vm, "main", strlen("main"));
gravity_vm_runclosure(vm, VALUE_AS_CLOSURE(main_fn), NULL, params, nparams);

gravity_value_t res = gravity_vm_result(vm);
// ...
```

This would allow this signature:

```swift
func main(args) {
  System.print(args);
}
```

Where `args` is now the original `argv`/`argc` translated into a `List` object.

**Comment by IngwiePhoenix** [comment]
A convenience macro may be used to simplify this process - i.e.: `VALUE_FROM_STRINGARRAY(_vm, _array, _len)`. It would essentially do what the first two lines of the above listing do and return a `gravity_value_t` immediately.

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/11efd1596a602c309339e902e6a16f080b885b2f
