### ISSUE TITLE
[need help] Embedding API

### ISSUE THREAD

**Issue by michal037** [marcobambini/gravity#236]
Hello!

~~In what file and place should I (and other people) add C code to extend the built-in VM classes?~~
Can you add this information to the [Embedding API](https://marcobambini.github.io/gravity/#/api) documentation?

The greatest advantage of this language is to run it from the C language. ~~Please, finish the documentation for us.~~ How to start with VM (Execute Gravity code from C)?

**Comment by felipetesc** [comment]
What I've written is far away from being complete and you should  read with extra cautious: yet, the following link may be proved useful:   https://github.com/felipetesc/gravity/tree/master/src/optionals

**Comment by IngwiePhoenix** [comment]
What exactly do you want to do, @michal037 ?

**Comment by michal037** [comment]
@IngwiePhoenix
aaah, I behaved like a donkey. When I read the documentation a long time ago, I did not have any tips on how to run a VM from C. How to start. Writing your own classes is ready on an example. Donkey from me.
