### ISSUE TITLE
buffer()

### ISSUE THREAD

**Issue by RootUp** [marcobambini/gravity#238]
File: /gravity/blob/master/src/runtime/gravity_core.c#L218

i.e
memcpy(buffer+pos, ":", 1);

Does not check `bufferoverflow()` while copying to destination.

**Comment by marcobambini** [comment]
It checks few lines earlier:
```c
// check if buffer needs to be reallocated
if (len1 + len2 + pos + 4 > len) {
    len = (len1 + len2 + pos + 4) + len;
    buffer = mem_realloc(NULL, buffer, len);
}
```
