### ISSUE TITLE
Unable to compile the gravity_parser.c

### ISSUE THREAD

**Issue by WorksOfBarry** [marcobambini/gravity#24]
Hi!

I am having some issues compiling the parser. Before I start, I should mention I am using an IBM i C compiler - you can [read more about its standards here](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzarf/hinst.htm), although I believe it is up to C99. This environment does not have make, so I am having to manually compile all the modules in order to create the ending object/program.

When I try compile `gravity_parser.c`, I am getting 5 compile errors when I which all relate to the same thing:

```
CZM0117: Operand must be a scalar type.

Cause . . . . . :   Valid scalar types include: signed and unsigned char;  
  signed and unsigned short, long, long long, and int; enum, float, double,
  long double, and pointers.                                               
Recovery  . . . :   Change the type of the operand, or use a different     
  operator.                                                                
```

All errors are pointing to `(gtoken_s)NO_TOKEN`

```
Line 1164: enum_value = (gnode_base_t *)gnode_literal_int_expr_create((gtoken_s)NO_TOKEN, enum_autoint);
Line 1365: gnode_t *outer_var = gnode_variable_create((gtoken_s)NO_TOKEN, string_dup(OUTER_IVAR_NAME), NULL, 0, NULL);
Line 1368: gnode_t *outer_decl = gnode_variable_decl_create((gtoken_s)NO_TOKEN, TOK_KEY_VAR, TOK_KEY_PRIVATE, 0, decls);
Line 2070: gnode_t *node= gnode_block_stat_create(NODE_LIST_STAT, (gtoken_s)NO_TOKEN, parser->statements);
Line 2138: return gnode_block_stat_create(NODE_LIST_STAT, (gtoken_s)NO_TOKEN, parser->statements);
```

The error is surely related to this systems compiler. I am not a C pro, so I was wondering if anyone could give me some pointers to what I should do to fix this.

Thanks,
Liam

**Comment by marcobambini** [comment]
Hi, I am quite sure the issues are related to a non C99 compiler. 
There should be some settings to force the compiler to use C99 mode, for example in gcc Makefile we added the -std=gnu99 flag.

**Comment by WorksOfBarry** [comment]
This is a compiler that IBM own and the only options for standards (language level) we get are `*ANSI` and `*EXTENDED`. 

I am under the assumption that this compiler is at the C99 standard, but missing some features (ILE C supports a subset of C99 features.). I will try and contact IBM to see if they can help.

Thanks!

**Comment by marcobambini** [comment]
@WorksOfBarry please keep my updated, I am sure we can fix the issues of that compiler

**Comment by WorksOfBarry** [comment]
Storing for future reference:

```
// -> /src/compiler/gravity_token.h
// -> From line 97

struct gtoken_s {
	gtoken_t			type;		// enum based token type
	uint32_t			lineno;		// token line number (1-based)
	uint32_t			colno;		// token column number (0-based) at the end of the token
	uint32_t			position;	// offset of the first character of the token
	uint32_t			bytes;		// token length in bytes
	uint32_t			length;		// token length (UTF-8)
	uint32_t			fileid;		// token file id
	bool				escaped;	// if true then string_unescape is called when token is finalized
	const char			*value;		// token value (not null terminated)
};

#define NO_TOKEN				(gtoken_s){0,0,0,0,0,0,0,0,NULL}
```

**Comment by marcobambini** [comment]
Compilation issue fixed?

**Comment by WorksOfBarry** [comment]
@marcobambini Not yet. It's currently being investigated, but I am just storing notes here for future reference.

**Comment by WorksOfBarry** [comment]
Test program to recreate the issue:

```

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef enum {
  // General (8)
  TOK_EOF = 0, TOK_ERROR, TOK_COMMENT, TOK_STRING, TOK_NUMBER, TOK_IDENTIFIER, TOK_SPECIAL, TOK_MACRO,

  // Keywords (36)
  // remember to keep in sync functions token_count and token_value
  TOK_KEY_FUNC, TOK_KEY_SUPER, TOK_KEY_DEFAULT, TOK_KEY_TRUE, TOK_KEY_FALSE, TOK_KEY_IF,
  TOK_KEY_ELSE, TOK_KEY_SWITCH, TOK_KEY_BREAK, TOK_KEY_CONTINUE, TOK_KEY_RETURN, TOK_KEY_WHILE,
  TOK_KEY_REPEAT, TOK_KEY_FOR, TOK_KEY_IN, TOK_KEY_ENUM, TOK_KEY_CLASS, TOK_KEY_STRUCT, TOK_KEY_PRIVATE,
  TOK_KEY_FILE, TOK_KEY_INTERNAL, TOK_KEY_PUBLIC, TOK_KEY_STATIC, TOK_KEY_EXTERN, TOK_KEY_LAZY, TOK_KEY_CONST,
  TOK_KEY_VAR, TOK_KEY_MODULE, TOK_KEY_IMPORT, TOK_KEY_CASE, TOK_KEY_EVENT, TOK_KEY_NULL, TOK_KEY_UNDEFINED,
  TOK_KEY_ISA, TOK_KEY_CURRFUNC, TOK_KEY_CURRARGS,

  // Operators (36)
  TOK_OP_SHIFT_LEFT, TOK_OP_SHIFT_RIGHT, TOK_OP_MUL, TOK_OP_DIV, TOK_OP_REM, TOK_OP_BIT_AND, TOK_OP_ADD, TOK_OP_SUB,
  TOK_OP_BIT_OR, TOK_OP_BIT_XOR, TOK_OP_BIT_NOT, TOK_OP_RANGE_EXCLUDED, TOK_OP_RANGE_INCLUDED, TOK_OP_LESS, TOK_OP_LESS_EQUAL,
  TOK_OP_GREATER, TOK_OP_GREATER_EQUAL, TOK_OP_ISEQUAL, TOK_OP_ISNOTEQUAL, TOK_OP_ISIDENTICAL, TOK_OP_ISNOTIDENTICAL,
  TOK_OP_PATTERN_MATCH, TOK_OP_AND, TOK_OP_OR, TOK_OP_TERNARY, TOK_OP_ASSIGN, TOK_OP_MUL_ASSIGN, TOK_OP_DIV_ASSIGN,
  TOK_OP_REM_ASSIGN, TOK_OP_ADD_ASSIGN, TOK_OP_SUB_ASSIGN, TOK_OP_SHIFT_LEFT_ASSIGN, TOK_OP_SHIFT_RIGHT_ASSIGN,
  TOK_OP_BIT_AND_ASSIGN, TOK_OP_BIT_OR_ASSIGN, TOK_OP_BIT_XOR_ASSIGN, TOK_OP_NOT,

  // Punctuators (10)
  TOK_OP_SEMICOLON, TOK_OP_OPEN_PARENTHESIS, TOK_OP_COLON, TOK_OP_COMMA, TOK_OP_DOT, TOK_OP_CLOSED_PARENTHESIS,
  TOK_OP_OPEN_SQUAREBRACKET, TOK_OP_CLOSED_SQUAREBRACKET, TOK_OP_OPEN_CURLYBRACE, TOK_OP_CLOSED_CURLYBRACE,

  // Mark end of tokens (1)
  TOK_END
} gtoken_t;

struct gtoken_s {
  gtoken_t type; // enum based token type
  uint32_t lineno; // token line number (1-based)
  uint32_t colno; // token column number (0-based) at the end of the token
  uint32_t position; // offset of the first character of the token
  uint32_t bytes; // token length in bytes
  uint32_t length; // token length (UTF-8)
  uint32_t fileid; // token file id
  bool escaped; // if true then string_unescape is called when token is finalized
  const char *value; // token value (not null terminated)
};
typedef struct gtoken_s gtoken_s;

#define NO_TOKEN (gtoken_s){0,0,0,0,0,0,0,0,NULL}

int main(int argc, char **argv) {
  gtoken_s test; // test
  test = (gtoken_s)NO_TOKEN;

  return;
}
```

**Comment by WorksOfBarry** [comment]
Next issue is with `src/runtime/gravity_vm.c`.

I am getting a lot of `CZM1268: Computed goto expressions are not supported.`

On lines including things like:

* `INTERPRET_LOOP`
* `DISPATCH()`
* among many others.

These macros are defined in `src/runtime/gravity_vmmacros.h`

* [`INTERPRET_LOOP`](https://github.com/marcobambini/gravity/blob/e8999a84efbd9c3e739bff7af39500d14e61bfbc/src/runtime/gravity_vmmacros.h#L135)
* [`DISPATCH()`](https://github.com/marcobambini/gravity/blob/e8999a84efbd9c3e739bff7af39500d14e61bfbc/src/runtime/gravity_vmmacros.h#L137)

Looks like this could be something else that the compiler doesn't support.

**Comment by marcobambini** [comment]
Seems like computed goto are not supported.
In gravity_value.h set macro GRAVITY_COMPUTED_GOTO to 0

**Comment by marcobambini** [comment]
Have you solved the NO_TOKEN macro compilation issue?
If not, just create a local gtoken_s var and set all its fields to 0 and use that var instead of the macro.

**Comment by WorksOfBarry** [comment]
Thanks for the suggestions. I solved the NO_TOKEN issue by removing the cast, which allowed it to compile.

I will try the GRAVITY_COMPUTED_GOTO to 0 tomorrow and let you know how it goes.

Thanks!

**Comment by WorksOfBarry** [comment]
The last fix was made to `src/utils/gravity_utils.c`.

Line 17 needed an extra condition to make it use `<sys/time.h>`.

```
#if defined(__linux) || defined(__ILEC400__) 
```

**Comment by WorksOfBarry** [comment]
We are now compiling the programs:

```
  CRTCMOD MODULE(&INTOLIB/UNITTEST) SRCSTMF('&U_SRC') &PARAMS
  CRTPGM PGM(&INTOLIB/UNITTEST) MODULE(&INTOLIB/*ALL) ENTMOD(*PGM)
  DLTOBJ OBJ(GRAVITY/UNITTEST) OBJTYPE(*MODULE)
  
  CRTCMOD MODULE(&INTOLIB/GRAVITY) SRCSTMF('&G_SRC') &PARAMS
  CRTPGM PGM(&INTOLIB/GRAVITY) MODULE(&INTOLIB/*ALL) ENTMOD(*PGM)
  DLTOBJ OBJ(GRAVITY/GRAVITY) OBJTYPE(*MODULE)
```

On both `CRTPGM`s
```
Definition not found for symbol 'remainder'.
Definition not found for symbol 'round'.    
Definition not found for symbol 'bzero'.    
Definition not found for symbol 'bzero'.    
```

ILE C / C++ do not have these functions, so I am having to find their equivalents.

```
remainder() -> fmod()
//fmod is floating point. GRAVITY_ENABLE_DOUBLE needs to be undefined [before here](https://github.com/marcobambini/gravity/blob/5a85b395fa04d4bb185027b4184032587cc66074/src/runtime/gravity_core.c#L1030).
```

**Comment by marcobambini** [comment]
For bzero:
#ifndef HAVE_BZERO
#define bzero(ptr,n)				memset(ptr, 0, n)
#endif

**Comment by WorksOfBarry** [comment]
I applied these lines:

```
#ifndef HAVE_BZERO
#define bzero(ptr,n)	memset(ptr, 0, n)
#endif
```

To the following headers:

* `src/runtime/gravity_vmmacros.h`
* `src/shared/gravity_memory.h`
* `src/compiler/gravity_lexer.h`
* `src/compiler/gravity_ircode.h`

Which, in result has removed the `bzero` binding issues.

**Comment by WorksOfBarry** [comment]
I applied these lines:

```
#ifdef __ILEC400__
#define remainder(a, b)	fmod(a, b)
#endif
```

To `src/runtime/gravity_core.c`

Which, in result has removed the `remainder` binding issue.

**Comment by WorksOfBarry** [comment]
Fix for round binding issue:

```
//src/runtime/gravity_core.c

double round_C99(double d) {
    double int_part, frac_part;
    frac_part = modf(d, &int_part);
    if(fabs(frac_part) < 0.5)
        return int_part;
    return int_part > 0.0 ? int_part + 1.0 : int_part - 1.0;
}

static bool function_float_round (gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) {
    #pragma unused(vm, nargs)
    
    #if defined(__ILEC400__)
            RETURN_VALUE(VALUE_FROM_FLOAT(round_C99(GET_VALUE(0).f)), rindex);
    #else
            #if GRAVITY_ENABLE_DOUBLE
                    RETURN_VALUE(VALUE_FROM_FLOAT(round(GET_VALUE(0).f)), rindex);
            #else
                    RETURN_VALUE(VALUE_FROM_FLOAT(roundf(GET_VALUE(0).f)), rindex);
            #endif
    #endif
}  
```

**Comment by marcobambini** [comment]
Very well done @WorksOfBarry!

**Comment by WorksOfBarry** [comment]
@marcobambini I will make a PR after some testing :)

**Comment by ejrjohn** [comment]
I have no clue what you are doing.

Edwin L Arnett

**Comment by WorksOfBarry** [comment]
@ejrjohn Trying to port Gravity to a system called IBM i which has it's own compilers. I am making all the necessary changes to get all the modules and programs to compile.

**Comment by WorksOfBarry** [comment]
The last issue we're having is actually reading the stream files - e.g. CCSID.

For example, I created `test.gravity` in the `test` directory:

```
hello world.
```

 and when I `call unittest 'test'`, the output is:

```
Test file: test.gravity                                  
Test path: test/test.gravity                             
SYNTAX ERROR on 0 (1,3): Expected expression but found %.
FAILURE                                                  
```

even though there is not a % in there. There may need to be a conversion process.

**Comment by ChrisHird** [comment]
Hi Working with Liam and attempting to get the unittest working. I have managed to work around the CCSID issues and EBCDIC conversions but now have a problem with another character test.
```
(01, 10) {: {   (offset: 10)                                                 
(02, 02) IDENTIFIER: name       (offset: 13)                                 
parse_literal_expression                                                     
(02, 06) :: :   (offset: 17)                                                 
        SYNTAX ERROR on 0 (2,9): Expected literal expression but found ERROR.
        FAILURE                                                              
```
This is the error that I am seeing from arguments_1.gravity, why is the error being generated on the colon?  The code is unfamiliar to me so parsing through all of the macros to find out the expected values is pretty long winded.  This appears to be the code segment returning the error.
```
static gnode_t *parse_literal_expression (gravity_parser_t *parser) {
	DEBUG_PARSER("parse_literal_expression");
	DECLARE_LEXER;
	
	gtoken_t type = gravity_lexer_next(lexer);
	gtoken_s token = gravity_lexer_token(lexer);
	
	if (type == TOK_STRING) {
		uint32_t len = 0;
		const char *value = token_string(token, &len);
		DEBUG_PARSER("STRING: %.*s", len, value);
		return gnode_literal_string_expr_create(token, value, len);
	}
	
	if (type == TOK_KEY_TRUE || type == TOK_KEY_FALSE) {
		return gnode_literal_bool_expr_create(token, (int32_t)(type == TOK_KEY_TRUE) ? 1 : 0);
	}
	
	if (type != TOK_NUMBER) {
		REPORT_ERROR(token, "Expected literal expression but found %s.", token_name(type));
		return NULL;
	}
	
	return parse_number_expression(token);
}  
```

Any guidance you can offer would be appreciated.

**Comment by marcobambini** [comment]
Hi, it does not make sense to me, the "but found ERROR" message means that instead of a valid token a TOKEN_ERROR is found so there should be something wrong in the lexer and that means that an invalid character set/sequence is found. But the file you are trying to parse is valid so I am 99% sure that the issue is still related to an invalid charset/conversion due to your configuration.

Is there a way I can have access to it?

**Comment by ChrisHird** [comment]
Unfortunately the system is sat behind a firewall with no access from outside. From my understanding this is returning the error when reading the colon? the printf statement you push out on debug seems to show it is reading the colon but the error is saying it should be a number? != TOK_NUMBER? Should this be finding the string and matching the first if statement? 

If I can do anything else let me know and I will run the test.

**Comment by marcobambini** [comment]
Try to set to 1 the GRAVITY_LEXER_DEGUB macro in debug_macros.h and try again.
You should see a more verbose debug output.

**Comment by ChrisHird** [comment]
I think I have found where the error may be?
static inline bool is_whitespace (int c) {
	return ((c == ' ') || (c == '\t') || (c == '\v') || (c == '\f'));
} 

in EBCDIC the \t == 0x05 ASCII 0x09 and I will need to convert the others.

**Comment by marcobambini** [comment]
Seems like a good candidate to me, even if I think that instead of trying to fix all these encodings issues what you should do is just to convert from EBCDIC to ASCII. Perhaps using: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.bpxbd00/e2as.htm
and then pass to the compiler the ASCII string.

**Comment by ChrisHird** [comment]
That link is for Z/OS we are running IBM i. The problem is the program is doing its comparison using EBCDIC character set internally (if c == ' ') is really saying (if c == 0x40 as 0x40 is a white space in EBCDIC). This is a program that is compiled using an EBCDIC compiler, we are translating the ASCII file to EBCDIC on read so it should match (other than where you have put in special characters \t\r\v etc or replaced the check with the ASCII hex value). I am still trying to see exactly what is being compared (HEX to HEX) which should work out if the conversion is working as it should.

**Comment by ChrisHird** [comment]
I have some tests which are stating success but have errors as well??
        Unknown character inside a string literal        
(06, 02) ;: ;   (offset: 92)                             
(06, 02) ;: ;   (offset: 92)                             
(06, 02) ;: ;   (offset: 92)                             
(08, 01) func: func     (offset: 95)                     
(08, 06) IDENTIFIER: f1 (offset: 100)                    
(08, 06) IDENTIFIER: f1 (offset: 100)                    
        SYNTAX ERROR on 0 (8,9): Expected ( but found {. 
        SUCCESS

**Comment by ChrisHird** [comment]
Marco,

IBM came back to us on the NO_TOKEN error. It appears it is not meeting the C++ standard? They have suggested a work around which fixes the problem, but I am now thinking maybe something else with the same kind of error is affecting the parser? Anyhow IBM suggested the following update to the code (I tested and it works) instead of casting the NO_TOKEN on each invocation.

#define NO_TOKEN (gtoken_s){TOK_EOF,0,0,0,0,0,0,0,NULL}

This is apparently due to the enumerator cast not working due to the first element being an int  (0) not an enumeration value. I could not find the relevant statements in the standard but I assume they are right?

Chris..

**Comment by marcobambini** [comment]
The two castings was an error and the source code was fixed some days ago, I'd suggest you to update to the latest version. Please note that only the NO_TOKEN definition is used in this way so I doubt others errors can be affected by this fix.
