### ISSUE TITLE
Is there any inheritance support?

### ISSUE THREAD

**Issue by stevefan1999** [marcobambini/gravity#242]
It is good to see that we can have a basic class and interface support.

**Comment by marcobambini** [comment]
@stevefan1999 inheritance is supported since the first version:
```
class foo {

}

class bar: foo {

}
```

I am exploring the possibility to add interface support, even if I am not so sure if it is a good idea because Gravity is really a duck type system so far (https://en.wikipedia.org/wiki/Duck_typing)

**Comment by stevefan1999** [comment]
@marcobambini 🤔Would you add this example to https://marcobambini.github.io/gravity/#/class
