### ISSUE TITLE
[Feaure Request] - Fibers as first class objects

### ISSUE THREAD

**Issue by felipetesc** [marcobambini/gravity#244]
Currently we have fibers as it follows, sample available at (https://marcobambini.github.io/gravity/#/fiber):
```swift
func main() {
        var fiber = Fiber.create({
            System.print("fiber 1");
            Fiber.yield()
            System.print("fiber 2");
        });

        System.print("main 1");
        fiber.call()
        System.print("main 2");
        fiber.call()
        System.print("main 3");
    }
```
My suggestion is to create a new syntax, perhaps,  such as:
```swift

Fiber AFibeName{

     init(){} //initialiaze variables accessible inside the var between yield and call??

    yield(){ throw Exception("Not implemented yield");}//the yield becomes the the create method seen above
    //call can accept params from outside so a thread can be feed with data ?
   call(params){ throw Exception("Not implemented call");}//something we want to do when the fiber.call is called
}
```

Or even:
```swift
fiber AFibeName(param1, param2...,paramN){
     System.print("fiber 1");
     yield();// or this.yield case we have a fiber inside another ????
     System.print("fiber 2");
}
```
So, we could call a given fiber only when we decide(not that we can't atm). 
IE, as well, this allows to create in a sort of way, a interface to a fiber, and use several times, and finally it seems cleaner. 

Uhm ?

Thank You!

**Comment by marcobambini** [comment]
Hi @felipetesc and thanks a lot for your suggestion.
Fibers work in a different way from what you suggested, it seems like we can introduce some of these concepts in a different class (not in Fibers). We have others priorities right now so I am going to close this issue request but I'll keep it saved in order to use it as a reference in a future release.
