### ISSUE TITLE
RUNTIME ERROR: Unknown LOADK index

### ISSUE THREAD

**Issue by lbuczkow** [marcobambini/gravity#246]
The following code works OK when called as `./gravity test.gravity`:

```
var data = [
	[
		"a": [10.12, 10.12121, 0.01012, 0.021],
		"b": [1.0101, 0.12021, 0.1021, 0.0 ],
		"c": [0.012012, -0.0101, -0.011, 0.01],
		"d": [102.12, 1.12, 0.011, 0.012]],
	[
		"a": [21.12012, 12.2001, 0.12212, 0.0],
		"b": [1.1121, -0.012, 0.12022, 0.0],
		"c": [0.12210, 0.012, 0.12022, 0.0],
		"d": [21.0, -0.0101212, 0.12022, 0.0]]]
		
func main() {
	System.print(data[1].a)	
}	
```

But fails with message `RUNTIME ERROR: Unknown LOADK index` when executed as bytecode: 

```
./gravity -c test.gravity -o test.g
./gravity -x test.g
```

However, the bytecode also works OK when some values are modified, for example when `data[1].d[1]` is changed from `-0.0101212` to `-0.0101202`.

**Comment by marcobambini** [comment]
@lbuczkow I am looking at this issue, I'll let you know soon. Thanks a lot for the report.

**Comment by marcobambini** [comment]
@lbuczkow fixed by 
https://github.com/marcobambini/gravity/commit/5a466d1699ea1838f70947dd14b4ca67c66b0780
