### ISSUE TITLE
Importing and exporting.

### ISSUE THREAD

**Issue by IngwiePhoenix** [marcobambini/gravity#256]
Hello!

I have seen the `include_test.gravity` file, but I wondered if it would be possible to implement an actual import/export mechanism that would allow a user to build proper modules?

Kind regards, Ingwie.

**Comment by marcobambini** [comment]
Yes sure, it is a planned feature. It has been discussed with some other users, we just trying to find out the best route for this functionality. Modules support is really important.

**Comment by IngwiePhoenix** [comment]
Mind linking me to said discussion? Or is it on Gitter? I'd like to join :)

**Comment by marcobambini** [comment]
Sure:
https://github.com/marcobambini/gravity/issues/62
and
https://github.com/marcobambini/gravity/issues/85
