### ISSUE TITLE
debug_macros.h: It will likely never find unistd.h on Windows.

### ISSUE THREAD

**Issue by IngwiePhoenix** [marcobambini/gravity#257]
https://github.com/marcobambini/gravity/blob/master/src/compiler/debug_macros.h#L19

This line is problematic. You probably should `#ifdef` for something like a Windows constant and not include this on Windows.

**Comment by IngwiePhoenix** [comment]
I could test on macOS. Although I do have MSVC on my Windows tablet, I am not all too fond of the MSVC CLI… I can access the tablet through SSH for simplicity, but I really, really dont like MSVC’s "setting variables first" idea, makes it hard to find the scripts for that. But, I could still attempt to test it, if you can tell me how do compile on the command line without having to go through the whole IDE. I never used that IDE, ever.

Version is 2017.

**Comment by marcobambini** [comment]
@IngwiePhoenix unistd.h is a file specifically added for Windows. It is located inside the gravity_visualstudio directory.

**Comment by IngwiePhoenix** [comment]
Oh, I did not see that. I was thinking of the UNIX standard’s file there. Thanks for letting me know. :)
