### ISSUE TITLE
Syntax errors on JSON deserialization

### ISSUE THREAD

**Issue by MarcoCicognani** [marcobambini/gravity#258]
I Marco, 
with your last committed version i tried to compile the inifinite loop tests and then i tried to execute them, but the json deserialization process fails due to an incorrect syntax of the file itself.
`SYNTAX ERROR on 0 (2,4): Expected } but found :.
SYNTAX ERROR on 0 (3,4): Expected } but found :.
SYNTAX ERROR on 0 (4,4): Expected expression but found :.
SYNTAX ERROR on 0 (5,4): Expected expression but found :.
SYNTAX ERROR on 0 (6,4): Expected expression but found :.
SYNTAX ERROR on 0 (7,4): Expected expression but found :.
SYNTAX ERROR on 0 (8,4): Expected expression but found :.
SYNTAX ERROR on 0 (9,4): Expected expression but found :.
SYNTAX ERROR on 0 (10,4): Expected expression but found :.
SYNTAX ERROR on 0 (11,4): Expected expression but found :.
SYNTAX ERROR on 0 (12,4): Expected expression but found :.
SYNTAX ERROR on 0 (13,4): Expected expression but found :.
SYNTAX ERROR on 0 (14,4): Expected expression but found :.
SYNTAX ERROR on 0 (16,4): Expected } but found : ...`
The compiled file is the follow, but it not contains really syntax errors:
`{
    "$moduleinit" : {
        "type" : "function",
        "identifier" : "$moduleinit",
        "tag" : 0,
        "nparam" : 0,
        "args" : false,
        "nlocal" : 0,
        "ntemp" : 1,
        "nup" : 0,
        "purity" : 0.500000,
        "bytecode" : "C40400003C040001",
        "lineno" : "0000000600000006",
        "pool" : [
            {
                "type" : "function",
                "identifier" : "main",
                "tag" : 0,
                "nparam" : 1,
                "args" : false,
                "nlocal" : 1,
                "ntemp" : 14,
                "nup" : 0,
                "purity" : 0.121212,
                "bytecode" : "2810000020140004BC101014300800042010000014100804201400011414080530180004301C000220201002100C1802480E001F30180005301C0002302000031004180224240002202800031428240A302C000A30300009283400012838000A10282C033024000A30180004301C000230200003100C18024400000C280800010C080000",
                "lineno" : "000000070000000700000007000000070000000700000007000000070000000700000007000000070000000700000007000000070000000700000007000000070000000700000008000000080000000800000008000000080000000800000008000000080000000800000007000000070000000700000007000000070000000A0000000A",
                "pool" : [
                    "iterate",
                    "next",
                    "Int",
                    "random",
                    100000000
                ]
            },
            "main"
        ]
    }
}`
I tried to compile and execute all the gravity test files, but he problem is always the same

**Comment by marcobambini** [comment]
@MarcoCicognani why have you closed this issue?

**Comment by MarcoCicognani** [comment]
@marcobambini because i noticed that '**-x**' option is needed to run compiled files, sorry for the useless issue

**Comment by marcobambini** [comment]
@MarcoCicognani no problem, the cli needs to be improved in many areas
