### ISSUE TITLE
cmake doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [marcobambini/gravity#259]
```
===>   Generating temporary packing list
ninja: error: unknown target 'install/strip'
```

FreeBSD 11.2

**Comment by yurivict** [comment]
gmake doesn't install anything either.

**Comment by marcobambini** [comment]
@yurivict I am not a cmake expert, any help on this?

**Comment by yurivict** [comment]
You need to add the ```install``` statements: https://cmake.org/cmake/help/v3.0/command/install.html

**Comment by marcobambini** [comment]
I added ```install(TARGETS gravity DESTINATION /usr/local/bin)``` can you please confirm that it works fine?

**Comment by yurivict** [comment]
It works, thanks!
