### ISSUE TITLE
Visual Studio Code syntax

### ISSUE THREAD

**Issue by Dohxis** [marcobambini/gravity#26]
Is anyone interested in extension for Visual Studio Code for syntax highlighting? I have simple extension already working, with minor modifications I could add it on Github if anyone is interested.

**Comment by marcobambini** [comment]
I can add a new folder to the official repository to collect syntax highlighting definitions.
Thanks!

**Comment by Dohxis** [comment]
Just published an extension, you can find it on vscode [marketplace](https://marketplace.visualstudio.com/items?itemName=Dohxis.gravity)! Only simple syntax highlighter for now.

**Comment by marcobambini** [comment]
Very well done, thanks!
