### ISSUE TITLE
Double free in gravity.

### ISSUE THREAD

**Issue by ibara** [marcobambini/gravity#261]
Hi --

gravity 0.6.0 exhibits a double free on OpenBSD when running the tests.
Relevant test log and gdb backtrace attached.
Let me know if you need anything else.
[gravity-bt-full.log](https://github.com/marcobambini/gravity/files/2674081/gravity-bt-full.log)
[test.log](https://github.com/marcobambini/gravity/files/2674083/test.log)

**Comment by marcobambini** [comment]
Thanks for re-running all the test suite.
Fixed by 
https://github.com/marcobambini/gravity/commit/b33bb56d36fb1004bbda923799d0b5fa78416c53
