### ISSUE TITLE
[RFC/Discussion] Callback syntax sugar 

### ISSUE THREAD

**Issue by IngwiePhoenix** [marcobambini/gravity#262]
Hello!

I am just asking for suggestions here, or rather, to start a discussion for syntactic sugar about callbacks.

With Gravity executing fibers sort-of asynchronously, implementing events wouldn't be that hard at all. Having an event-enabled routine execute something in the background, and calling the assigned callback would not be a problem. This is in part a reference to #9.

I have those two suggestions:

```
// Lua-like block arguments:
obj.on("eventName") {|e| /*...*/}

// ECMAScript 6+-like arrow-functions:
obj.on("eventName") => (e) {/*...*/}
```

The likely easier to implement is the first one, while the second is more verbose and would likely introduce more logic to the parser.

What are your ideas? I'd love what others think. :)

**Comment by marcobambini** [comment]
Gravity already has this features, it is the bind method.
`obj.bind("name", closure);`

See bind.gravity in test/unittest
