### ISSUE TITLE
[RFC/Discussion] Reserve "$" for resolving environment variables

### ISSUE THREAD

**Issue by IngwiePhoenix** [marcobambini/gravity#263]
This is a suggestion to utilize `$` to resolve environment variables. This is probably rather easy to resolve within the parser - that every expression starting with `$` is automatically a reference to an environment variable and should result in `getenv` - or `putenv`/`setenv` - calls.

```
$ cat file.g
print($MY_VAR);

$ MY_VAR=1337 ./gravity file.g
1337
```

(Don't mistake this - I did not implement it, I just displayed it as what it would be like.)

The above code would translate to something like this:

```
CALL print
  PARAMS [ EXPR "$MY_VAR" ]

->
CALL print
  PARAMS [ CALL FUNCTION getenv PARAMS [ "MY_VAR" ] ]
```

Optionally, the environment could be imported into the program on startup as a map - so the value could essentially be "cached" into the VM already, reducing the `getenv` calls down to simple map-gets.

What's your thoughts on this?

**Comment by marcobambini** [comment]
The $ sign is already internally used and I do not like the idea to introduce hacks and add complications to the parser just to replace two simple calls. The best way to proceed would be to add the putenv/getenv methods to the System class.
