### ISSUE TITLE
surpport utf-8/unicode strings

### ISSUE THREAD

**Issue by liigo** [marcobambini/gravity#266]
It's not clear in docs which encoding was used in gravity string.

Seems like it just surpport ASCII strings now.

Hope to be improved.

**Comment by marcobambini** [comment]
@liigo UTF-8 strings are fully supported:
```
func main() {
    var s = "Hello 😎❤️😎 World";
    System.print(s);
}
```

**Comment by liigo** [comment]
Will `string.split()` works as expected then? 

```
var s = "Hello 😎❤️😎 World";
s.split(", ");
```
