### ISSUE TITLE
[Feature request] Deprecated macro

### ISSUE THREAD

**Issue by IngwiePhoenix** [marcobambini/gravity#267]
Hello!

I'd like to request a specific macro that may come in handy especially in projects that use Gravity over a long time and have breaking changes. For example:

```
#deprecated "Will be removed in next version"
func foo() {
  // ...
}
```

It'd be useful to have such a macro :)

Kind regards,
Ingwie

**Comment by IngwiePhoenix** [comment]
After reading my way through the parser, here is a more elaborate request. Note - I am not very good on parsers, and I have never written one myself. So what I will do here is declare the code below as "conceptual code".

```c
// Add MACRO_DEPRECATED
// Tell the compiler to mind a function's "is_deprecated" field.

void parse_macro_deprecated(gravity_parser_t* parser) {
  DECLARE_LEXER;

  // Syntax:
  // '#deprecated' STRING_LITERAL
  // function_declaration
  //
  // Example:
  // #deprecated "Deprecated since version x.y.z. Use other function instead."
  // func foo() {}
  //
  // Maybe this applies to classes and class methods too?
  // Like this:
  // #deprecated "Use Bar instead."
  // class Foo {
  //   #deprecated "This method is deprecated in favor of .gusto()"
  //   func like() {}
  //   func gusto() {} // <-- Deprecation does not apply here.
  // }

  bool hasMessage = (gravity_lexer_peek(lexer) == TOK_STRING);
  gtoken_t token = gravity_lexer_next(lexer);

  if(!hasMessage) {
    REPORT_ERROR(token, "Expected a string, but got a %s instead.", token_name(token));
    return;
  }

  const char* message;
  message = cstring_from_token(parser, token);

  if(gravity_lexer_token(lexer) != TOK_FUNC) {
    REPORT_ERROR(token, "Expected a function following the #deprecated, but got a %s instead.", token_name(token));
    return;
  } else {
    // Parse next statement and obtain the following declaration's gnode_t
    gnode_t *targetNode = parse_function(...);
    targetNode->is_deprecated = true;
    targetNode->deprecationMessage = message;
  }
}
```

Now when the compiler generates the bytecode, it may add the deprecation warning to the prior to the call to display it. For instance:

```swift
#deprecated "Use bar() instead."
func foo() {}
func bar() {}

func main() {
  System.print("Use bar() instead."); // <-- Injected
  foo(); // <-- actual
}
```

**Comment by marcobambini** [comment]
Perhaps this macro will be useful in the future but I really don't see any reason to add it to the current version. I'd like to keep the language implementation as simple as possible and I am more than willing to add to Gravity all the useful features that can improve the language itself. Adding a features just because maybe in the future it could be used doesn't seem a good way to manage our limited time.

What do you think?
Can we close this issue and keep here for future reference?

**Comment by IngwiePhoenix** [comment]
Yes :) This feature can be implemented some time in the future too - it is not important or mandatory. But something you may want to consider at some point again.
