### ISSUE TITLE
Change isa to is

### ISSUE THREAD

**Issue by 1DC** [marcobambini/gravity#27]
`something isa Int` doesn't flow as well as `something is Int`

**Comment by marcobambini** [comment]
Thanks @1DC for the feedback.
isa means "is a" instance of that class so I really think it is the right name to use.

**Comment by 1DC** [comment]
"is a instance" still doesn't really make a lot of sense. "is an" would be more appropriate.

Completely removing a(n) makes it a lot less awkward to read.

**Comment by neysofu** [comment]
I agree with @1DC. Also, "isInstance" is a common idiom in computing.

**Comment by marcobambini** [comment]
It is a common shortcut in computer science.

**Comment by 1DC** [comment]
Either that or completely remove `isa` and replace it for something like `typeof(x) == Int`.

**Comment by Dohxis** [comment]
I think `is`  would be the best solution, it reads well and isn't long. Would prefer it over `isa` and `typeof()`.

**Comment by marcobambini** [comment]
Seems like "is" is winning as a replacement for "isa".
Any objection?

**Comment by SysVoid** [comment]
@marcobambini `is is Ftw`

**Comment by 1DC** [comment]
Posted on the wrong account. :D
@marcobambini `is is Ftw`

**Comment by hallzy** [comment]
I personally prefer isa, as it is a computer science term, and to me "is" sounds like more of an assignment.

Either works though

**Comment by 1DC** [comment]
Another alternative perhaps could be `instanceof`. `x instanceof Foo`

**Comment by neysofu** [comment]
`instanceOf` sounds like a conversion to me. I would go with Scala's `isIstanceOf`.

**Comment by 1DC** [comment]
**Somewhat on-topic but somewhat off-topic.**

I'm confused how `instanceOf` or `is` can seem like an assignment. If anyone has time, mind dropping me an email with some info about that? I never studied CS officially, I've just got a lot of experience. :P

admin@preprocess.uk

**Comment by Dohxis** [comment]
Yes it doesn't look like assignment for me either.

**Comment by rohmishra** [comment]
If we are talking about keeping the current style and just changing the operator name, is sounds much much better IMO.

**Comment by marcobambini** [comment]
Operator **isa** has been renamed **is** with my latest commit.

**Comment by praisethemoon** [comment]
Object Pascal already has `is` operator. Well done. 👍 :1st_place_medal:
