### ISSUE TITLE
I try to compile in visual studio and I get unresolved _gravity_env_free and others...

### ISSUE THREAD

**Issue by johnshadow23** [marcobambini/gravity#279]
I try to compile in visual studio and I get 
unresolved external symbol _gravity_env_free
unresolved external symbol _gravity_env_name
unresolved external symbol _gravity_env_register
unresolved external symbol _gravity_isenv_class

**Comment by marcobambini** [comment]
Seems like gravity_env.c is missed from the target.

As a workaround just comment the line:
#define GRAVITY_INCLUDE_ENV
in gravity_optionals.h

**Comment by johnshadow23** [comment]
Sorry for got background on this, I tried to compile the DLL and CLI they both still give me this error.

**Comment by marcobambini** [comment]
Fixed by #https://github.com/marcobambini/gravity/commit/a801e0bd45a90686634f19a98ed592cbc3d5b96a
