### ISSUE TITLE
Segfault on master

### ISSUE THREAD

**Issue by ibara** [marcobambini/gravity#282]
Hi --

Running `./gravity -t test` after building on a fresh checkout of master causes a segfault.

Compiler is clang-8.0.0, OS is OpenBSD/amd64.

Test log and gdb backtrace attached.

Thanks!
[gravity-gdb.txt](https://github.com/marcobambini/gravity/files/3323394/gravity-gdb.txt)
[gravity-test.txt](https://github.com/marcobambini/gravity/files/3323395/gravity-test.txt)

**Comment by marcobambini** [comment]
Hi @ibara and thanks for you report.
Do you know what is the unit test that triggers the crash?
