### ISSUE TITLE
Using gravity on Constrained Device

### ISSUE THREAD

**Issue by cszawisza** [marcobambini/gravity#284]
Hi!

I want to be able to send, compiled on a desktop machine, bytecode to a MCU that by it's own has no compiler build-in, is it doable? If not, what kind of steps need to be taken to achieve that?

**Comment by marcobambini** [comment]
Hello, yes sure it is possibile. Just compile Gravity executable to JSON and then send the JSON to the MCU unit. On that unit you need to have gravity runtime installed in order to execute the bytecode.

You can find more information in https://marcobambini.github.io/gravity/#/quickstart
```
To compile a gravity file to a exec.json executable:
./gravity -c myfile.gravity -o exec.json

To execute a precompiled json executable file:
./gravity -x exec.json
```
