### ISSUE TITLE
Please expand/improve c-embedding/import documentation

### ISSUE THREAD

**Issue by shionhart** [marcobambini/gravity#287]
Can you please expand on the steps following:

Creating a c file, like the one in your documentation

    // report error callback function
    void report_error (error_type_t error_type, const char *message,
                       error_desc_t error_desc, void *xdata) {
        printf("%s\n", message);
        exit(0);
    }

    // function to be executed inside Gravity VM
    bool my_function (gravity_vm *vm, gravity_value_t *args,
                      uint16_t nargs, uint32_t rindex) {
        // do something useful here
    }

    // Configure VM delegate
    gravity_delegate_t delegate = {.error_callback = report_error};

    // Create a new VM
    gravity_vm *vm = gravity_vm_new(&delegate);

    // Create a new class
    gravity_class_t *c = gravity_class_new_pair (vm, "MyClass", NULL, 0, 0);

    // Allocate and bind closures to the newly created class
    gravity_closure_t *closure = gravity_closure_new(vm, my_function);
    gravity_class_bind(c, "myfunc", VALUE_FROM_OBJECT(closure));

    // Register class inside VM
    gravity_vm_setvalue(vm, "MyClass", VALUE_FROM_OBJECT(c));`

Then creating a groovy file

    func main() {
        // allocate a new class
        var foo = MyClass();

        // execute the myfunc C function
        foo.myfunc();
    }

Is the groovy file complete or do I need to import something? Do I need to compile and run the c file? I apologize if I missed something in the documentation.

**Comment by shionhart** [comment]
This is the documentation I'm referring to: https://marcobambini.github.io/gravity/#/api

**Comment by ripanioan** [comment]
Hi @shionhart, that code snippet that you are referring to is not **Groovy** code.
It's **Gravity** code.
The documentation is teaching you how to add new classes in **Gravity virtual machine** and use them in Gravity. 
**This is not related to Groovy.**

**Comment by shionhart** [comment]
The question is related to gravity... I mistyped in my original post and wrote "groovy" instead of "gravity". Your comment comes off as really condescending even when it should be easy to figure out what I meant given the context of the code snippet given and the name of this repository.
