### ISSUE TITLE
Please, help wih embedding api

### ISSUE THREAD

**Issue by darkoverlordofdata** [marcobambini/gravity#289]
Hi, I'm trying to create a native class with instance methods, as described here: https://marcobambini.github.io/gravity/#/api

When I try to run this example, I run into both compile time and run time issues:

    1) compile issue
    warning: incompatible pointer types passing 'bool (gravity_vm *, gravity_value_t *, uint16_t, uint32_t)' (aka 'bool (struct gravity_vm *, gravity_value_t *, unsigned short, unsigned int)') to parameter of type 'gravity_function_t *' [-Wincompatible-pointer-types]
    [build]     gravity_closure_t *closure = gravity_closure_new(vm, my_function);
    [build]                                                          ^~~~~~~~~~~

    2) runtime issue
    Since it is a warning and not an error, I try running the example script anyway, but, (no surprise) I get 'Segmentation fault'.
    
I tried the example code in api/exec_c.c, and it works, but it demonstrates static methods, not instance methods. When I delve into the source code, I see the real code for wrapping instance methods is quite different than the example code on the website - I realize that this can easily happen when a library is still in development, can you update the example on the website, or post in your reply, code to do this that reflects the current state of the api?

**Comment by darkoverlordofdata** [comment]
I finally figured this out, the api example at https://marcobambini.github.io/gravity/#/api is wrong. 

The raw c function cannot be directly given to the closure:

    // Allocate and bind closures to the newly created class
    gravity_closure_t *closure = gravity_closure_new(vm, my_function);
    gravity_class_bind(c, "myfunc", VALUE_FROM_OBJECT(closure));


First it needs to be placed in a function wrapper:

    // Allocate and bind closures to the newly created class
    gravity_closure_t *closure = gravity_closure_new(vm, gravity_function_new_internal(NULL, NULL, my_function, 0));
    gravity_class_bind(c, "myfunc", VALUE_FROM_OBJECT(closure));

**Comment by marcobambini** [comment]
Yes you are right, I need to update the `api` section.
Please always refer to the code contained in `gravity_core.c`
