### ISSUE TITLE
Int + String + Int returns Int

### ISSUE THREAD

**Issue by txgruppi** [marcobambini/gravity#29]
I'm not sure this is an error or a design choice but the code below returns `(INT) 10`. Shouldn't it not compile because we're trying to sum different types?

```gravity
class Point {
  var _x;
  var _y;

  func init(x, y) {
    _x = x;
    _y = y;
  }

  func String() {
    return _x + "x" + _y;
  }
}

func main() {
  var point = Point(5, 5);
  return point.String();
}
```

Forgive me if this is a a feature of the language, I just started testing some code.

**Comment by marcobambini** [comment]
It makes sense and this is a feature/drawback of the dynamically typed language.
Your code _x + "x" + _y is interpreted as ((_x + "x") + _y) from left to right.

So _x + "x" in executed by operator_int_add and the second "x" is converted to an int (0 in this case), the result of this operation (5) is then added to _y which is 5 again and the end result is 10.

A better String func for a Point class could be:
func String() {
     return "(" + _x + ", " + _y + ")";
}

Leftmost operator is a String "(" so everything else is converted to String too.

**Comment by 1DC** [comment]
I would definitely expect the output of that to be a String, not an Int.

**Comment by 1DC** [comment]
![img](https://transfer.sh/169gJb/chrome-2017-03-07-17-51-50.png)
