### ISSUE TITLE
ENV Documentation

### ISSUE THREAD

**Issue by runeimp** [marcobambini/gravity#291]
I came across Gravity by its recent addition to Homebrew. Looked like a nice language for embedding. So I was doing a basic review of the language and wasn't even sure if it supported accessing environment variables (nothing mentioned on the website or GitHub I searched for) until I found <https://github.com/marcobambini/gravity/blob/7b9284eb9945f5d1a63fe13dea88d5f3c26c58dc/src/optionals/gravity_opt_env.c> and then guessed I could access them with `ENV.get("VAR_NAME")`.

I know docs are a pain. I'll see about contributing. Hopefully this is a good pointer until that happens though. 👼

**Comment by marcobambini** [comment]
Hi @runeimp, yes you are right, I could improve documentation :-)
The environment module is an optional C module (that you can omit from the compilation) and it contains three class methods:

```
// read an env variable
var value = ENV.get("VAR_NAME")

// write an env value
ENV.set("VAR_KEY", "VAR_VALUE")

// list all env variables
var list = ENV.keys()
```

Any contribution to the official documentation is more than welcome.
Adding documentation is easy, just modify/create a markdown file in the docs directory and link this file in the `_sidebar.md` file.
