### ISSUE TITLE
Can't compile example on macOS

### ISSUE THREAD

**Issue by runeimp** [marcobambini/gravity#292]
I tried to compile the [C example](https://github.com/marcobambini/gravity/blob/master/examples/Executing%20Gravity%20from%20C.md) and am getting errors. This is on OS X 10.14.6 Mojave. I have the `example.c` in a directory next to my clone of the repo. So `gravity/examples/example.c` next to `gravity/repo`. This is what I've tried:

```bash
RuneImps-iMac:examples runeimp$ gcc -ansi -I ../repo/src/compiler -I ../repo/src/runtime -I ../repo/src/shared -I ../repo/src/utils example.c -o example
Undefined symbols for architecture x86_64:
  "_gravity_compiler_create", referenced from:
      _main in example-347e1a.o
  "_gravity_compiler_free", referenced from:
      _main in example-347e1a.o  "_gravity_compiler_run", referenced from:      _main in example-347e1a.o  "_gravity_compiler_transfer", referenced from:      _main in example-347e1a.o  "_gravity_core_free", referenced from:
      _main in example-347e1a.o
  "_gravity_value_dump", referenced from:
      _main in example-347e1a.o
  "_gravity_vm_free", referenced from:
      _main in example-347e1a.o
  "_gravity_vm_new", referenced from:
      _main in example-347e1a.o
  "_gravity_vm_result", referenced from:
      _main in example-347e1a.o
  "_gravity_vm_runmain", referenced from:
      _main in example-347e1a.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The problem seems to be that Gravity is complaining it doesn't support `x86_64`. I find that hard to believe. But I have done very little with C before and have seen no discussion of what options to use with the GCC compiler for the example. Any help would be appreciated.  👼 

I have a gist of the code to review if needed at <https://gist.github.com/runeimp/de84eed440efbd6026a7fdc843505a64>
Maybe I have a typo I'm not seeing?

**Comment by marcobambini** [comment]
Hello @runeimp I just tried the code within Xcode and everything works as expected.
I see that you included the correct headers and the example.c file but you completely omitted all the Gravity sources.

I added the example.c file to the examples directory and I modified the Makefile so you can now automatically compile the example target. Just execute:
`make example`
