### ISSUE TITLE
Gamedev usage

### ISSUE THREAD

**Issue by amerkoleci** [marcobambini/gravity#294]
Hi,
Excellent work on the language, really like the swift semantic, I would like to integrate it into my game engine for game scripting logic, but would like to know how does it fit in gamedev world.

1) Does the language has struct to pointer mapping logic like swift: 
```
let vertexData: [Float] = [
   0.0,  1.0, 0.0,
  -1.0, -1.0, 0.0,
   1.0, -1.0, 0.0
]
let dataSize = vertexData.count * MemoryLayout.size(ofValue: vertexData[0]) // 1
vertexBuffer = device.makeBuffer(bytes: vertexData, length: dataSize, options: [])
```
2) Can vertex data be struct with different layout, lets say Vector3 Position; Vector2 UV; etc? Same struct can be sent to shaders as well.
3) Are there any examples on how to extend with C++ and C functions?
4) Is it possible to extend C++ class from gravity language?

Thanks in advance,
Amer

**Comment by amerkoleci** [comment]
Any news here?

**Comment by marcobambini** [comment]
Hi @amerkoleci, there is no FFI support (not yet) so the correct way to proceed would be to create a Class and then bind C code to access all the required native code/structs. I am thinking about a way to transparently use C from within Gravity but I haven't any solution ready.

3. Take a look at the files in the `examples` folder

4. What do you mean by 'extend' ?
