### ISSUE TITLE
how to build it on windows with gcc(MinGW) and get .a file ?

### ISSUE THREAD

**Issue by acnologia000** [marcobambini/gravity#295]
how can i build gravity on windows to get .a and .h files to embed in other tools ? 
also i would like for more detailed examples for embedding api along with compilation instructions

**Comment by marcobambini** [comment]
Thanks to @foobit you can now use CMake to build static libraries on Windows.
If you are not familiar with CMake there is also a GUI helper available from https://cmake.org
