### ISSUE TITLE
Public macros with C++ compatibility

### ISSUE THREAD

**Issue by foobit** [marcobambini/gravity#300]
Gravity integration with C++ projects work great except for a few **VALUE_FROM** macros.

The following public facing macros use _designated initializers_ which is not supported in C++ (_unless you use C++20_):
- `VALUE_FROM_ERROR`
- `VALUE_FROM_OBJECT`
- `VALUE_FROM_INT`
- `VALUE_FROM_FLOAT`
- `VALUE_FROM_NULL`
- `VALUE_FROM_UNDEFINED`
- `VALUE_FROM_BOOL`
- `STATICVALUE_FROM_STRING`

I looked into doing a pull request using the same pattern as `gravity_string_to_value` to hide the inline initializers in c code.  However, this will require additional code changes in places where VALUE_FROM requires an _l-value_.

e.g. gravity_core.c `range_loop` uses `&VALUE_FROM_INT(...)`

What are your thoughts on this?

**Comment by marcobambini** [comment]
I didn't know that this issue exists with C++.
I tried the following C++ example:

```c++
#include <iostream>
#include "gravity_value.h"
#include "gravity_macros.h"

int main(int argc, const char * argv[]) {
    gravity_value_t value = VALUE_FROM_NULL;
    
    return 0;
}
```

And I obtained a linker error: `Undefined symbol _gravity_class_null`.
Is this error related to the issue you are reporting?

**Comment by foobit** [comment]
## Test project
https://github.com/foobit/cppdi


## C++ designated initializers
Looks like designated initializers support for C++ depends on platform, C++ dialect and compiler version.

## Windows 10
- Building for: Visual Studio 16 2019
- The C compiler identification is MSVC 19.26.28806.0

**C++11**
> set (CMAKE_CXX_STANDARD 11)
```
..\src\main.cpp(6): error C7555: use of designated initializers requires at least '/std:c++latest'
..\src\main.cpp(6): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
```

_**Note:** even set to C++20 MSVC seems to not fully support it._
> set (CMAKE_CXX_STANDARD 20)
```
..\src\main.cpp(6): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
```
---
MinGW
- The C compiler identification is GNU 8.1.0
- The CXX compiler identification is GNU 8.1.0

_**gcc 8+** support C+2a features_
```
succeeds
```

---
## Ubuntu 18.04
- The C compiler identification is GNU 7.5.0
- The CXX compiler identification is GNU 7.5.0

_**Note:** GNU 7.5.0 only supports up to C++17_
> set (CMAKE_CXX_STANDARD 17)
```
src/main.cpp: In function ‘int main(int, const char**)’:
gravity/src/shared/gravity_macros.h:46:97: sorry, unimplemented: non-trivial designated initializers not supported
 #define VALUE_FROM_NULL                     ((gravity_value_t){.isa = gravity_class_null, .n = 0})
                                                                                                 ^
src/main.cpp:6:29: note: in expansion of macro ‘VALUE_FROM_NULL’
     gravity_value_t value = VALUE_FROM_NULL;
                             ^~~~~~~~~~~~~~~
```

**Comment by foobit** [comment]
> I didn't know that this issue exists with C++.
> I tried the following C++ example:
> 
> ```c++
> #include <iostream>
> #include "gravity_value.h"
> #include "gravity_macros.h"
> 
> int main(int argc, const char * argv[]) {
>     gravity_value_t value = VALUE_FROM_NULL;
>     
>     return 0;
> }
> ```
> 
> And I obtained a linker error: `Undefined symbol _gravity_class_null`.
> Is this error related to the issue you are reporting?

```cpp
#include "gravity_value.h"
#include "gravity_macros.h"
#include "gravity_core.h"

int main(int, const char**)
{
    gravity_core_init();

    gravity_value_t value = VALUE_FROM_NULL;

    return 0;
}
```
Looks like MacOS linker strips out `gravity_core.c` in your example. Add the above to force linkage.

**Comment by marcobambini** [comment]
Does it work for you on MacOS? It does not work for me.

**Comment by foobit** [comment]
Adding the call `gravity_core_init();` in your above example will fix your linker issue for MacOS.  Once you do that, your test example will compile and run fine.

Is seems that MacOS uses clang and allows for C++ designated initializers. I don't have a current Mac (I don't use it much) so I don't know the exact clang version or default settings that allows for this.

This looks like an issue only for **Visual Studio** and **gcc** _(pre v8.0)_

**Comment by marcobambini** [comment]
Well I tried several times with Xcode but it does not work (I suspect an issue in Xcode itself). Anyway I am sure it should work.

So, since it seems a Visual Studio/gcc < 8 only issue, can I assume that this issue should not be fixed? What are your thoughts?

**Comment by foobit** [comment]
I'm primarily using Gravity on Windows with Visual Studio in C++. So I'm unable to use the above macros in their current state.

Gravity is being used in my project as an embedded scripting language, so those macros are used very frequently.  My current workaround is writing C++ safe function replacements within my own code base _(and just ignoring those macros)_.

IMO, I think **it should be fixed** as to not limit Gravity to specific compilers and versions.  Without fixing this issue you would have to document that Gravity does not fully support Visual Studio or older versions of gcc.  Those macros aside, Gravity currently works with every modern C/C++ compiler which is nice.

I could do a pull request that would change those inline macros to internal functions. However, my hesitation is that I do not yet know enough of the internals of the project to understand the impact of performance or side-effects.

**Comment by marcobambini** [comment]
I agree, so in that case I would add special cases for Visual Studio in C++ on Windows only.
Something like:
```c
#ifdef __cplusplus
#ifdef _MSC_VER

// fix for Visual Studio C++ designated initializers
#define VALUE_FROM_NULL   gravity_value_t value_from_null (...)
....

#endif
#endif
```

What do you think?

**Comment by foobit** [comment]
Sounds good, I'll do a pull request with the changes.
