### ISSUE TITLE
Reading arbitrary Gravity class instance properties in C

### ISSUE THREAD

**Issue by foobit** [marcobambini/gravity#302]
Consider the following Gravity source:
```swift
extern var ColorFunctions;

class Color {
    public var r;
    public var g;
    public var b;

    func init(_r, _g, _b) {
        r = _r;
        g = _g;
        b = _b;
    }
}

func main() {
    var someColor = Color(0xff, 0x20, 0x80)

    ColorFunctions.swizzle(someColor)
}
```

Defining the class method `ColorFunctions.swizzle` in C would be as follows:
```c
gravity_class_t *c = gravity_class_new_pair(vm, "ColorFunctions", NULL, 0, 0);
gravity_class_t *c_meta = gravity_class_get_meta(c);
gravity_class_bind(c_meta, "swizzle", color_swizzle_handler);
gravity_vm_setvalue(vm, "ColorFunctions", VALUE_FROM_OBJECT(c));
```
Ok, so far that works great. Now for the _tricky_ part implementing `color_swizzle_handler`.

As the class `Color` is completely written in Gravity, C does not know about it. However, I would like to duck-type the properites:
```c
bool color_swizzle_handler(gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) {
    if (VALUE_ISA_INSTANCE(args[1])) {
        gravity_instance_t *inst = VALUE_AS_INSTANCE(args[1]);

        // Red
        gravity_value_t r = VALUE_NOT_VALID;
        gravity_value_t* propR = gravity_hash_lookup(inst->objclass->htable, VALUE_FROM_CSTRING(vm, "r"));
        if (propR && VALUE_ISA_CLOSURE((*propR))) {
            gravity_function_t *funcR = VALUE_AS_CLOSURE(*propR)->f;
            r = inst->ivars[funcR->index];
        }

        // Green
        gravity_value_t g = VALUE_NOT_VALID;
        gravity_value_t* propG = gravity_hash_lookup(inst->objclass->htable, VALUE_FROM_CSTRING(vm, "g"));
        if (propG && VALUE_ISA_CLOSURE((*propG))) {
            gravity_function_t *funcG = VALUE_AS_CLOSURE(*propG)->f;
            g = inst->ivars[funcG->index];
        }

        // Blue
        gravity_value_t b = VALUE_NOT_VALID;
        gravity_value_t* propB = gravity_hash_lookup(inst->objclass->htable, VALUE_FROM_CSTRING(vm, "b"));
        if (propB && VALUE_ISA_CLOSURE((*propB))) {
            gravity_function_t *funcB = VALUE_AS_CLOSURE(*propB)->f;
            b = inst->ivars[funcB->index];
        }

        // TODO: do something with (r, g, b) if they are all valid
    }

    return true;
}
```
So the `color_swizzle_handler` handler does indeed work however. I have three related questions:
1. Why is `someColor` parameter on index 1 `args[1]`? I would assume it would be `0`.  In the debugger `nargs == 2`. That seems to indicate index not number of arguments.
2. As I said it works reading arbitrary properties. Is there a simpler way to do this? Is there cases where it will not work?
3. What is the proper action for handling errors in this case? For example, a class didn't match or a number was passed in. Would I just call `RUNTIME_ERROR(...)`?

**Notes**
If I could confirm that the instance is the class `Color`, could I skip the hash lookup for each property? It looks like the indexes are in declaration order.  However, I assume that is not safe if the underlining byte-code could change.

Also the inverse of `gravity_instance_setivar` does not exist. I would have used `gravity_instance_getivar` in the above example.

`GRAVITY_API gravity_value_t     gravity_instance_getivar (gravity_instance_t *instance, uint32_t idx);` does not seem to exist.

**Comment by marcobambini** [comment]
Hello @foobit, I added the new `gravity_instance_lookup_property` function that take cares of all the details. It returns VALUE_NOT_VALID if the property does not exists.

Using the new function you can rewrite your `color_swizzle_handler ` in a much simpler way:
```c
static bool color_swizzle_handler(gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) {
    if (!VALUE_ISA_INSTANCE(args[1])) RETURN_ERROR("Unable to process non-instance parameter");
    
    gravity_instance_t *inst = VALUE_AS_INSTANCE(args[1]);
    
    // RED
    gravity_value_t red = gravity_instance_lookup_property(vm, inst, VALUE_FROM_CSTRING(vm, "r"));
    if (VALUE_ISA_NOTVALID(red)) RETURN_ERROR("Unable to find r property");
    
    // GREEN
    gravity_value_t green = gravity_instance_lookup_property(vm, inst, VALUE_FROM_CSTRING(vm, "g"));
    if (VALUE_ISA_NOTVALID(green)) RETURN_ERROR("Unable to find g property");
    
    // BLUE
    gravity_value_t blue = gravity_instance_lookup_property(vm, inst, VALUE_FROM_CSTRING(vm, "b"));
    if (VALUE_ISA_NOTVALID(blue)) RETURN_ERROR("Unable to find b property");
    
    // for example returns the sum of the colors
    RETURN_VALUE(VALUE_FROM_INT(red.n + green.n + blue.n), rindex);
}
```

Now your questions:

1. args[0] is always the `self` parameter, in your case it is the `ColorFunctions` class.
2. use the new `gravity_instance_lookup_property`
3.  RETURN_ERROR macro is the correct way to handle an error condition inside your c code

I would use the lookup method because I cannot guarantee the index of the ivar inside the instance (it should remain an implementation detail).

**Comment by foobit** [comment]
Ah perfect! I was pretty close on implementation details. The checking for a getter was the missing bit. Thanks!

**Comment by marcobambini** [comment]
Yes right, your implementation was almost fine.
