### ISSUE TITLE
Embedding API: option to expose C classes without requiring extern

### ISSUE THREAD

**Issue by foobit** [marcobambini/gravity#305]
With Gravity one can do the following:
```swift
System.print("hello, world")
```
Without adding:
```swift
extern var System // this would actually cause a redeclaration error
```
However to expose my **C** defined classes, `extern` is required.

I am building an extensive **C** API exposed to Gravity. I would like to auto register those classes like the System class.  To avoid a potentially large `extern` list for Gravity scripts.

Is there a gravity embedded function that I can use auto register my common used classes?

**Comment by marcobambini** [comment]
Right, that's because `gravity_core_register` and `gravity_optional_identifiers` are automatically called when vm is created.
What do you think about introducing a new callback in gravity_delegate_t with the same prototype as `gravity_optional_identifiers` ?

**Comment by foobit** [comment]
Ah, I see in the source now. Yes, adding a delegate like `gravity_optional_identifiers` that I can supply additional extern identifiers would be great.

**Comment by marcobambini** [comment]
Well, it turns out that I had already implemented that callback.
It is called `optional_classes` in the `gravity_delegate_t` and the prototype is identical to `gravity_optional_identifiers`.

Let me know if it works for your case.

**Comment by foobit** [comment]
The `optional_classes` work great. Thanks!
