### ISSUE TITLE
gravity_delegate_t.error_callback reports incorrect line numbers when Gravity source has comments

### ISSUE THREAD

**Issue by foobit** [marcobambini/gravity#308]
The following script:
```swift
// some comment
this is invalid code
```
Will report semantic error `Identifier this not found.` _line 3_.

However:
```swift
var a = 1
this is invalid code
```
Will report semantic error `Identifier this not found.` _line 2_ which is correct.

This is also an issue with block comments:
```swift
/*
Comment
*/
this is invalid code
```
Will report semantic error `Identifier this not found.` _line 6_.

**Comment by marcobambini** [comment]
How do you test this code?
The following script:
```swift
// some comment
this is invalid code
```
correctly reports `SEMANTIC ERROR on 0 (2,1): Identifier this not found.`

**Comment by foobit** [comment]
Ok found the issue: On Windows, text files lines have line feed and carriage return. It looks like the parser does not strip the endings correctly with comments.

You can test this on Unix with "C" source:

```c
const char* src0 = "// some comment\r\nthis is invalid code";
const char* src1 = "var a = 1\r\nthis is invalid code";
```
the string `src0` reports the incorrect error line number. `src1` reports the error line number correctly.

**Comment by marcobambini** [comment]
Good catch!
Fixed by https://github.com/marcobambini/gravity/commit/4c50fff8b52e8ea20d05be7dc35e6777ec74b62e
