### ISSUE TITLE
Suggestion: Pipes

### ISSUE THREAD

**Issue by Dohxis** [marcobambini/gravity#31]
Hello community. I have a suggestion - Pipe operator. It would be a syntactic sugar for nested functions. Pipe operator is widely used in functional programming (for example `Elm`, `Elixir`, `F#`, `Haskell`) and it gives code really clean look and makes everything way more readable.

Imagine this:
```swift
String.split(String.capitalize(String.reverse("Gravity is awesome!")));
```  
with pipe operator it would look like
```elixir
"Gravity is awesome!"
    |> String.reverse()
    |> String.capitalize()
    |> String.split()
```
which I think is way better! What do you think? Comment and maybe suggest your ideas.

**Comment by neysofu** [comment]
Even better — I still haven't read the compiler, so I don't know wether it can be done easily — would be to allow custom operators, for a full functional flavour. At that point, adding the pipe operator to the standard library is trivial.

**Comment by Dohxis** [comment]
No because you can pass additional arguments to every function.

**Comment by rohmishra** [comment]
As @Dohxis said. For example String.substr(2,5).


Also, i wish is supported |> and not hammer in then

**Comment by rohmishra** [comment]
*js

**Comment by marcobambini** [comment]
@Dohxis why not simply:
```swift
"Gravity is awesome!".reverse().capitalize()split()
```
