### ISSUE TITLE
Gravity LNK2001 on VS2019

### ISSUE THREAD

**Issue by Sevenisko** [marcobambini/gravity#311]
Hello, I've implemented the Gravity language into one project and compiles correctly. But somehow the Gravity is linked correctly with GNU compilers, but on VS2019 it throws 8 unresolved symbol errors.

`
1>gravity.lib(gravity_core.obj) : error LNK2001: unresolved external symbol __imp__fmax
1>gravity.lib(gravity_core.obj) : error LNK2001: unresolved external symbol __imp__remainder
1>gravity.lib(gravity_core.obj) : error LNK2001: unresolved external symbol __imp___time64
1>gravity.lib(gravity_core.obj) : error LNK2001: unresolved external symbol __imp__round
1>gravity.lib(gravity_utils.obj) : error LNK2001: unresolved external symbol __imp__feof
1>gravity.lib(gravity_opt_math.obj) : error LNK2001: unresolved external symbol __imp__cbrt
1>gravity.lib(gravity_opt_env.obj) : error LNK2001: unresolved external symbol __imp___putenv_s
1>MSVCRT.lib(chandler4gs.obj) : error LNK2001: unresolved external symbol __except_handler4_common
`

How to fix that?

**Comment by marcobambini** [comment]
See accepted answer here: https://stackoverflow.com/questions/334896/clrdump-c-error-lnk2019-unresolved-external-symbol-imp-registerfilter8
