### ISSUE TITLE
Java bindings?

### ISSUE THREAD

**Issue by MrManiacc** [marcobambini/gravity#317]
Hi, I know this is a bit off topic, and you probably won't be able to help but it's worth a try. I was wondering how I would go about getting this working in java? Could you possible make bindings or point me in the direction for making bindings? I'm a very big fan of the this language for game development, and I'm mainly a java developer (kotlin). I haven't messed around to much with making binding for java bindings to a C lib, but I know it's possible. I've done some research on the subject but everything is 5 or 6 years out of date. I would LOVE if we could get some natives bindings for java, and if you can't do it your self, some general guide would be extremely helpful. Thank you for making this awesome language, and if you have some free time please look into making some bindings, I know a ton of people who would love to see this done. Thanks again!!!

**Comment by nougator** [comment]
You can create your own binding.

**Comment by nougator** [comment]
And I don't know if java can use native libs.

**Comment by vuvk** [comment]
@MrManiacc, you can use JNI, JNA or JavaCPP for do it

**Comment by marcobambini** [comment]
@MrManiacc @nougator @vuvk I just added a sample Objective-C binding project to Gravity.

You can follow its code as a starting point to re-create a binding for another language like Jave.
I also added some notes about a possible Java implementation in the README file.

More at: https://github.com/marcobambini/gravity/tree/master/binding
