### ISSUE TITLE
How to embed?

### ISSUE THREAD

**Issue by nougator** [marcobambini/gravity#325]
Hey, I want to know how to embed gravity on a application, I didn't find the doc very clear about it.

**Comment by RobLoach** [comment]
While the documentation isn't really there, there is an example:
https://github.com/marcobambini/gravity/blob/master/examples/example.c

**Comment by marcobambini** [comment]
Thanks @RobLoach 
@nougator please note that I just updated the official documentation:
https://marcobambini.github.io/gravity/#/embedding
