### ISSUE TITLE
stat check

### ISSUE THREAD

**Issue by tfarina** [marcobambini/gravity#326]
There seem to be a problem with the following line of code:

if (stat(path, &sb) > 0) return -1;

According to the man page of stat(2), in case of success, zero is returned, otherwise on error, -1 returned. If I don't get this wrong, I would say the check should be against ' < 0 '.

**Comment by marcobambini** [comment]
You are right!
Fixed by https://github.com/marcobambini/gravity/commit/77c8b403cb04a84357c77a4ea4e989a62d76ab12
Thanks a lot!
