### ISSUE TITLE
Inconsistency in the API (underscore_case vs camelCase)

### ISSUE THREAD

**Issue by markand** [marcobambini/gravity#339]
Hi,

I was looking at the API offered by Gravity, it looks like the File module uses a mix of underscore_case and camelCase (isEOF) even though the overall API uses camelCase only. Shouldn't this be fixed?

https://github.com/marcobambini/gravity/blob/73d8837c6fd85c0759e21a4a4d72d0e49112651e/src/optionals/gravity_opt_file.c#L425

**Comment by marcobambini** [comment]
Well yes, you are right. Let me check if there are any other inconsistencies in the code.

**Comment by marcobambini** [comment]
Thanks @markand.
Fixed by https://github.com/marcobambini/gravity/commit/dd4990e97f5f05f987a26fb4216f11269522559c
