### ISSUE TITLE
Get value for computed 

### ISSUE THREAD

**Issue by DevulderJeanPaul** [marcobambini/gravity#341]
hi,
it's possible in future 
write a example for computed_property_create with setter function ?
i have problem  when writing property value
thanks,

**Comment by marcobambini** [comment]
Hello @DevulderJeanPaul,
not sure to understand.

You mean an example in Gravity or in C?

**Comment by DevulderJeanPaul** [comment]
> Hello @DevulderJeanPaul,
> not sure to understand.
> 
> You mean an example in Gravity or in C?

Hi Marco,

In C please, I try create a computed setter but when I try read arguments (integer value) got invalid value

**Comment by marcobambini** [comment]
@DevulderJeanPaul can you please post your code here?

**Comment by DevulderJeanPaul** [comment]
static bool setValue (gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex)
{
    gravity_value_t value = args[1];

    printf("args value = %lld",value.n); // doesn't display 11 value like the below example code

    RETURN_NOVALUE();
}
  
void
setup_foo(gravity_vm *vm)
{
    gravity_class_t *c = gravity_class_new_pair(NULL,"Gfx",NULL,0,0);

    gravity_closure_t *closure = NULL;

    closure = computed_property_create(NULL, NULL,NEW_FUNCTION(setValue));

    gravity_class_bind(c, "xx", VALUE_FROM_OBJECT(closure));

    gravity_vm_setvalue(vm,"Gfx",VALUE_FROM_OBJECT(c));
}

// gravity code

extern var Gfx

func main()
{
	var h = Gfx()
	
	h.xx = 11

}

**Comment by marcobambini** [comment]
Your code is right, there was a bug in the Gravity code, now fixed by https://github.com/marcobambini/gravity/commit/f67c05b18c14778ee17853430dfe6774dc98e33b.

Thanks a lot!
