### ISSUE TITLE
after installing the latest version 0.8.1 gravity commands do not work

### ISSUE THREAD

**Issue by cfsavant** [marcobambini/gravity#347]
after installing the latest version 0.8.1 gravity commands do not work.
I cannot figure out how to install an older version.
mac osx: 10.15.7
brew install gravity

gravity sync
 $ gravity sync
Error loading file sync

same thing with gravity login and all other commands.

**Comment by marcobambini** [comment]
I am not sure to understand.
sync and login does not exists, you should pass a filename to the gravity command line tool.

**Comment by cfsavant** [comment]
This is resolved
