### ISSUE TITLE
Passing arguments to gravity programs

### ISSUE THREAD

**Issue by WilliamBehrens** [marcobambini/gravity#349]
Maybe I'm missing something but when ever I try and pass a program I have written in Gravity, it doesn't matter if I call gravity <file> or have a '#!/usr/bin/gravity' at the beginning it always gives me a  'Error loading file <argument>'.

You can find the program I'm trying to run here https://gitlab.com/WilliamBehrens/darkmagic/-/blob/master/proj

**Comment by IngwiePhoenix** [comment]
In:
```swift
func main(){
    for(var i in _args) {
        parseArgs(_args[i]);
    }
    System.exit(0);
}
```

you have to use `ENV.argv` :)
See: https://marcobambini.github.io/gravity/#/env?id=class-constants

**Comment by WilliamBehrens** [comment]
@IngwiePhoenix it appears that either works (if you check the tests it's actually what they use there), but, that didn't fix the issue.
