### ISSUE TITLE
Unresolved external symbols when compiling cli/dll ?

### ISSUE THREAD

**Issue by Uberwire99** [marcobambini/gravity#351]
So, I've cloned the repo in my working directory, ran Visual Studio 2019, opened up the Solutions and tried building, but got the following errors. Why do they occur and how to fix them?

![image](https://user-images.githubusercontent.com/68770854/113634003-469a0500-966e-11eb-95a3-c59942b89ca6.png)

**Comment by marcobambini** [comment]
@Uberwire99 the file gravity_opt_file.c is missed from the Visual Studio 2019 project. Please add it to the VC project and try to compile again.

**Comment by Uberwire99** [comment]
> 
> 
> @Uberwire99 the file gravity_opt_file.c is missed from the Visual Studio 2019 project. Please add it to the VC project and try to compile again.

Can you please specify the exact destination? Adding it to the root of the VC project creates more errors.
![image](https://user-images.githubusercontent.com/68770854/113789054-b24ba300-973e-11eb-9746-e16e3b9e2b8e.png)

Compiling simply results in a lot of error output. I don't think that single file missing is the cause here... Can you make this project compatible for VS2019 please? I'm looking forward to using Gravity for an extension to C.

**Comment by marcobambini** [comment]
I updated the project to Visual Studio 2019 and everything compiled just fine.
No need to add `gravity_opt_file.c` because it was already included in the original project.
Commit is https://github.com/marcobambini/gravity/commit/184d0965e2233908aab5ee712c3671011ddfbfc8

**Comment by Uberwire99** [comment]
It compiles without an error! Thanks! Quick question, I'm using CMake for my project and wonder whether I need a special include directory or just the .lib generated by compilation?

**Comment by marcobambini** [comment]
You should be OK with .lib generated by the compilation.
