### ISSUE TITLE
[MinGW] Makefile doesn't set compiler properly

### ISSUE THREAD

**Issue by SarahIsWeird** [marcobambini/gravity#353]
Hey! I had to edit the Makefile for Gravity to compile. I'm not sure if it's a quirk of MinGW, but it tried to compile with a program ``cc``. This is the line that's problematic: https://github.com/marcobambini/gravity/blob/master/Makefile#L9

Maybe make should try to find a compiler on the system? As a suggestion, it could try to execute ``gcc``, ``clang`` and ``msvc``, and look if any of them are actually executed. Alternatively, the documentation could be updated to specify that a compiler can be set with ``make CC=clang`` or whatever the actual compiler may be.

**Comment by marcobambini** [comment]
Hi @SarahIsWeird can you please make that changes and submit a pull request?

**Comment by SarahIsWeird** [comment]
I was hesitant to work on this, as I couldn't actually get a program to execute on Windows, but this was caused by [this issue](https://github.com/marcobambini/gravity/issues/350).

I'll have a think about this issue. I have a "working" prototype, but the problem I see with it is that the Makefile will become a lot larger. MinGW, the main reason this issue exists, is just gcc cross-compiling to Windows, so the problem I see with it is making it work with MSVC. Do you care about that? Anybody using MSVC would probably compile with with Visual Studio anyways, right?

**Comment by SarahIsWeird** [comment]
I don't think this issue is worth pursuing right now. I've come up with a working version, but I don't see the use in it. Compiling with MSVC should probably be done via CMake anyways, and clang has problems with the `-lm` flag, which I don't know enough about to fix myself. Oh well 🤷‍♀️
