### ISSUE TITLE
[Feature] #include additional search directories

### ISSUE THREAD

**Issue by MikeRKing** [marcobambini/gravity#356]
Hi there,

Firstly I've only recently discovered Gravity and really like it, and will be leveraging it in a project I'm developing. Before I deep dive too much into the codebase to start hopefully contributing, I was wondering if the following feature could be considered;

When using #include it is my understanding that it will search the current working directory for the included files.

Although specifying additional search directories would be amazing (and would certainly make this request redundant), do you think it could be added that not only does it search the current working directory, but if the current working directory is not the same directory as the executable, also search the directory the executable exists in.

Use case;

script.gravity exists in my folder 'project' but the program responsible for compiling it exists in 'gravity'.  Upon #include "stuff.gravity" first the compiler will search 'project' if the file exists, though if not, it will search the folder 'gravity'.

This will allow for a base of include files which can be utilised by any script regardless of it's location, and providing it searches the cwd before the program directory, it shouldn't conflict.

**Comment by marcobambini** [comment]
The default behavior can be easily customized by setting the `loadfile_callback` of the `gravity_delegate_t`.
This callback is called each time an `#include` statement is parsed.

It is up to the developer to customize the search directories algorithm starting from the filename/path passed as first argument of the callback.

**Comment by MikeRKing** [comment]
> The default behavior can be easily customized by setting the `loadfile_callback` of the `gravity_delegate_t`.
> This callback is called each time an `#include` statement is parsed.
> 
> It is up to the developer to customize the search directories algorithm starting from the filename/path passed as first argument of the callback.

That's excellent to learn. Thanks :)
