### ISSUE TITLE
Question: How to bind a class method that returns a new object

### ISSUE THREAD

**Issue by untoldengine** [marcobambini/gravity#360]
Hi @marcobambini 

I have another question.

Let's say in a gravity file you perform the following vector3n operation

```
var a=vector3n(1.0,0.0,1.0);  //line 1
var b=vector3n(2.0,1.0,0.0); //line 2
var c= a + b;  //line 3. var c never gets the proper result. The result gets lost somewhere. ????
``` 

The vector3n is a custom C++ class and has operator overloading such as "+".

My question is, how would you bind a class method so that it is capable of returning a new object as shown in line 3?

I was playing around with this yesterday by following your code examples but the return value gets lost the moment that this line of code is executed:

```
RETURN_VALUE(VALUE_FROM_OBJECT(...), rindex);
``` 

From what I can tell, I have to create a new instance and use "gravity_instance_setxdata" but I'm not too sure.

Thanks in advance.

**Comment by marcobambini** [comment]
Take a look at `operator_string_add` in `gravity_core.c`.
The trick is to register a closure with the special `GRAVITY_OPERATOR_ADD_NAME` name.

**Comment by untoldengine** [comment]
Hi @marcobambini 

Thanks for the code snippet. I was able to get it to work.
I am able to bind a method that adds two vectors and returns the resulting vector, for example:

```
//addition.gravity
var v2=Vector3n(1.0,2.0,1.0);
var v3=Vector3n(4.0,1.0,2.0);
var v1=v2+v3;  //result is correct
```

However, even though it works, I think I'm missing something crucial or I'm implementing it incorrectly. 

I'm still trying to get a feel for Gravity and right now I'm just deducing how things work by going through your code examples. I'm basically just hacking my way through lol.

Do you mind reviewing the code below and tell me if I'm doing it correctly? I'm sure I'm missing something crucial.

```
static bool operator_vector3n_add (gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) {

    //code to bind the addition of two vectors. i.e. v1=v2+v3
    //create a new instance for the resulting vector (v1). Not sure if this is the proper way to do it.
    gravity_class_t *c=gravity_class_new_pair(vm, "Vector3n", NULL, 0, 0);
    
    gravity_instance_t *v1 =gravity_instance_new(vm, c);
    
    //get the two vector arguments
    gravity_instance_t *v2 = (gravity_instance_t *)GET_VALUE(0).p;
    gravity_instance_t *v3 = (gravity_instance_t *)GET_VALUE(1).p;
    
    // get xdata for both vectors
    Vector3n *vector2 = (Vector3n *)v2->xdata;
    
    Vector3n *vector3= (Vector3n *)v3->xdata;
    
    //add the vectors
    Vector3n vector1=*vector2+*vector3;
    
    //create a new vector type
    Vector3n *r = new Vector3n(vector1.x,vector1.y,vector1.z);
    
    //setting the vector data to v1
    gravity_instance_setxdata(v1, r);
    
    RETURN_VALUE(VALUE_FROM_OBJECT(v1), rindex);
    
}
```

Thanks

**Comment by marcobambini** [comment]
Hi @untoldengine 

It was almost correct except for the `gravity_class_new_pair`, which does not need to be re-executed.
You already have the class `Vector3n` registered inside the VM, so you can lookup it using `gravity_vm_getvalue` or `gravity_vm_lookup,` or you can just save a global reference to the registered `Vector3n` class (like I did in gravity_core.c) and use it every time you need that class inside your Vector3n.c file (this is the recommended way).

```swift
static bool operator_vector3n_add (gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) {
    
    // get the two vector arguments
    gravity_instance_t *v1 = (gravity_instance_t *)GET_VALUE(0).p;
    gravity_instance_t *v2 = (gravity_instance_t *)GET_VALUE(1).p;
    
    // get xdata for both vectors
    Vector3n *vector1 = (Vector3n *)v1->xdata;
    Vector3n *vector2 = (Vector3n *)v2->xdata;
    
    // add the vectors
    Vector3n v = *vector1 + *vector2;
    
    // create a new vector type
    Vector3n *r = new Vector3n(v.x, v.y, v.z);

    // lookup class "Vector3n" already registered inside the VM
    // a faster way would be to save a global variable of type gravity_class_t *
    // set with the result of gravity_class_new_pair (like I did in gravity_core.c -> gravity_core_init)

    // error not handled here but it should be checked
    gravity_class_t *c = VALUE_AS_CLASS(gravity_vm_getvalue(vm, "Vector3n", strlen(Vector3n)));

    // create a Vector3n instance
    gravity_instance_t *result = gravity_instance_new(vm, c);

    //setting the vector data to result
    gravity_instance_setxdata(result, r);

    RETURN_VALUE(VALUE_FROM_OBJECT(result), rindex);
}

```

**Comment by untoldengine** [comment]
Hey @marcobambini 

Thank you so much. 

After sending you the question, I did more testing and realized that my implementation was failing. So, I was certain I was doing something wrong.

Your solution helped and solved other issues that were arising.

Thank you so much. I appreciate it.
