### ISSUE TITLE
Reordering and sorting headerfiles for simpler documentation.

### ISSUE THREAD

**Issue by tDwtp** [marcobambini/gravity#366]
I  want to reorder headerfiles (and maybe *.c files) in order to make them more readable.
I also found an overloaded function, which i want to rename: `gravity_function_deserialize` inside `shared/gravity_value`.
```c
uint32_t            gravity_function_deserialize_buffer (const char*, size_t, uint32_t*);
gravity_function_t *gravity_function_deserialize_json (gravity_vm*, json_value*);
```
respectively. (this helps portability).
Later on the line i might add support for TinyCC from bellard (which is my main compiler).*
I also want to change the cli to dynamically link to the `gravityapi.dll/so`**

Merge follows in a minute (messed up my branching).

\* \[related issue added later]
\*\* \[related issue added later]

**Comment by tDwtp** [comment]
see #367 for sorting functions inside headerfiles

**Comment by tDwtp** [comment]
Never mind the renaming. I missread the part with the `gravity_function_deserialize`/`gravity_bytecode_deserialize`.

**Comment by marcobambini** [comment]
Pull request accepted thanks.
