### ISSUE TITLE
Question: Calling a class method from an application

### ISSUE THREAD

**Issue by untoldengine** [marcobambini/gravity#371]
Hi @marcobambini 

Need a clarification once again.

Consider a gravity script as shown below:

```
func init(){
//Code here...
}

func update(dt){
//Code here...
}

```

I'm able to call the update() gravity function from my engine using one of the examples I found in your repo. The example is shown below:

```
void callUpdate(double dt){

 gravity_value_t update_function = gravity_vm_getvalue(vm, "update", (uint32_t)strlen("update"));
        if (!VALUE_ISA_CLOSURE(update_function)) {
            printf("Unable to find update function into Gravity VM.\n");

        }else{

            // convert function to closure
            gravity_closure_t *update_closure = VALUE_AS_CLOSURE(update_function);

            // prepare parameters

            gravity_value_t p1 = VALUE_FROM_FLOAT(dt);
            gravity_value_t params[] = {p1};

            // execute init closure
            if (gravity_vm_runclosure (bindManager->vm, update_closure, VALUE_FROM_NULL, params, 1)) {

            }
        }
}
```

My question is, how would you call a method that belongs to a class?

For example, I want to call the update() method in this gravity script. But I want to call it from my engine:

```
class Player:U4DModel{

func init(){

}

func update(dt){

}

}

```

I tried different variations of your code example but I am unable to call the update() method from my engine.

Any help is truly appreciated.

Thanks

**Comment by marcobambini** [comment]
Hi @untoldengine,
just a clarification: you want to call the `update` method of an instance of the `Player` class written in Gravity from within your C++ code, right?

**Comment by untoldengine** [comment]
Hi @marcobambini 

Yes. That is exactly right. Is that possible?

**Comment by marcobambini** [comment]
Hi @untoldengine,

The most challenging part is to get a reference to the right instance.
Once you get the instance, it is easy to lookup for a closure (`gravity_class_lookup_closure`) and then executes it (`gravity_vm_runclosure`).

A way could be to register a class from C++ to Gravity and then expose that instances to it with a key that can be looked up in C++ with a hash table.

I don't know the overall architecture of your project, but a more powerful way could be to use the delegate bridge API, which I successfully used with Creo. Unfortunately, the delegate bridge APIs are not yet documented. Still, they offer a way to create a fully-featured bridge between Gravity and an external language (we used it from Objective-C).

**Comment by untoldengine** [comment]
Hi @marcobambini 

Thanks. I'm going to look into it. I'll keep you post it.

**Comment by untoldengine** [comment]
Hi @marcobambini 

Thanks for your help. I think I almost got it working. There are some parts of the implementation that are not working quite well yet, but before I look into them, I need to confirm that what I'm doing is correct, I guess for a sanity check.

Is line 2  the correct way to get the Closure from the instance (model_instance)? Notice that I had to use `gravity_value_getclass` and `VALUE_FROM_OBJECT`.

I am able to call the update method of the instance but I can tell that some other part of the code is failing.

```
//line 1.
STATICVALUE_FROM_STRING(key, "update", (uint32_t)strlen("update"));
       
//line 2. 
gravity_closure_t *update_closure = (gravity_closure_t *)gravity_class_lookup_closure(gravity_value_getclass(VALUE_FROM_OBJECT(model_instance)), key);

//line 3.
if (update_closure==nullptr) {

    U4DLogger *logger=U4DLogger::sharedInstance();
    logger->log("Unable to find update method into Gravity VM");

}else{
    gravity_value_t p1 = VALUE_FROM_FLOAT(dt);
    gravity_value_t params[] = {p1};

//Line 4.
    // execute closure
    if (gravity_vm_runclosure (vm, update_closure, VALUE_FROM_NULL, params, 1)) {

    }
}
```

**Comment by untoldengine** [comment]
I think I fixed the issue that I was having. I was not setting the sender in the `gravity_vm_runclosure`. So it seems to work now.

Either way, I would love for you to review the code snippet in the previous comment just to make sure that I am not missing anything. 

```
if (gravity_vm_runclosure (vm, update_closure, VALUE_FROM_OBJECT(model_instance), params, 1)) {

 }
```

**Comment by marcobambini** [comment]
Hi @untoldengine,

Your code is perfect!

How did you manage to get a reference to the right instance in C++?

**Comment by untoldengine** [comment]
Hi @marcobambini 

I ended up using a simple C++ map as a dictionary. During the instantiation of the object, I store the unique ID of the model as the key and store the gravity_instance as a value. So, whenever the game engine calls the update() method on the entity, I search for the gravity instance using the unique ID. Once I have the gravity_instance, I give that to Gravity which calls the appropriate update() method in the script. Works quite well.

I just encountered a weird issue. For some reason, you can't create two instances of a class in gravity (see code snippet below). 

In line 1, I create an instance of a Player class. The Player class inherits its behaviors from U4DModel. The instance is created by gravity just fine.

However, line 2 shows the creation of another instance of a Player class. But for some weird reason, Gravity completely ignores this object. That is, it doesn't even call the binding functions associated with the class. No gravity_instance is created nothing. Again, is like Gravity completely ignores the creation of the second instance of a class.

Now, line 3, creates an instance of the Field class. The Field class inherits its behaviors from the U4DModel. This instance gets created just fine. The gravity binding functions are called and there is no problem.

Now, guess what happens if I try to create a second instance of the Field class (line 4)? The problem arises again, the second instance gets completely ignored by Gravity. 

Any insight on what can be happening?

```
func init(){

  //Line 1. Create first instance of Player class.
  var a=Player();  //Player is a subclass of U4DModel
  a.initModel("player0");

  //Line 2. Create second instance of Player class. THIS SNIPPET IS NEVER CALLED BY GRAVITY
  var b=Player(); //Player is a subclass of U4DModel
  b.initModel("oppositeplayer0");

  //Line 3. Create Instance of Field class.
  var c=Field();  //Field is a subclass of U4DModel
  c.initModel("field");

 //Line 4. Create second Instance of Field class. AGAIN this is never called by gravity
  var d=Field();  //Field is a subclass of U4DModel
  d.initModel("field2");
}
```

**Comment by marcobambini** [comment]
Hmm it is a weird issue.
Is the U4DModel a C++ class?

**Comment by untoldengine** [comment]
Hi @marcobambini 

Here is a video that I recorded that shows the problem:

https://youtu.be/xwmCo1ELFyc

So as the video show, it seems the problem is in fact with the subclass. 


Answering your questions:
 
The U4DModel class is a C++ class in my game engine. All the bindings have been set up with gravity.
The Player class is a subclass of U4DModel. This class is declared in a gravity script and its definition looks as shown below:
The loadModel() is a U4DModel method. Notice that in line 1 I use self.loadModel to call the method.


```
class Player:U4DModel{

func init(){

}

func initModel(n){

  //line 1. call the parent loadModel() method
  if(self.loadModel(n)){
  
  }

}

func update(dt){

  
}

}

```

This morning, I did a quick test and decided to make my game models instances of U4DModel as shown below. And guess what? Both models do show up, as expected.

```
func init(){

  var a=U4DModel();
  a.loadModel("player0");

  var b=U4DModel();
  b.loadModel("oppositeplayer0");

}
```

So, to reiterate the problem.

When I declare two instances of the same subclass, as shown below, Gravity ignores the creation of the second instance.


```
func init(){

  var a=Player();
  a.initModel("player0");
  
  var b=Player();
  b.initModel("oppositeplayer0");

}
```

**Comment by marcobambini** [comment]
Hi @untoldengine,

I really enjoyed watching your video, thanks a lot for sharing!

I think to have identified the problem in this code:
```swift
func initModel(n){
  //line 1. call the parent loadModel() method
  if(self.loadModel(n)){
     ...
  }
}
```
The correct call should be:
```swift
func initModel(n){
  //line 1. call the parent loadModel() method
  if(super.loadModel(n)){
     ...
  }
}
```
because you want to force the execution of a super method.

I haven't yet discovered why it silently fails (I need to investigate a bit more what is happening in this case).

Please let me know if it fixes your issue.

**Comment by untoldengine** [comment]
Hi @marcobambini 

Unfortunately, it did not fix the issue.

The issue happens before calling `super.loadModel`. It happens upon the instantiation of the second object. I have verified this by simplifying the code to its bare bones. 

In the code snippet below, I instantiate both subclasses and set a breakpoint on the appropriate binding method in my engine.
Only the first instance encountered gets created. The second instance gets ignored. 

It seems as if Gravity only allows ONE instance of a subclass to ever be created, just like a Singleton.

```
func init(){

 var a=Player();  //The instance gets created. The gravity binding method gets called.
 var b=Player(); //This instance does not get created. In fact, the gravity binding method never gets called.

}
```

If it helps, this is the binding method that gets called upon instantiation of the object:

```
bool U4DScriptBindModel::modelCreate(gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex){
        
        // self parameter is the model create in register_cpp_classes
        gravity_class_t *c = (gravity_class_t *)GET_VALUE(0).p;
        
        // create Gravity instance and set its class to c
        gravity_instance_t *instance = gravity_instance_new(vm, c);
        
        U4DModel *model = new U4DModel();
       
        // set cpp instance and xdata of the gravity instance
        gravity_instance_setxdata(instance, model);
        
        // return instance
        RETURN_VALUE(VALUE_FROM_OBJECT(instance), rindex);
    }
```

Your help is much appreciated.

**Comment by marcobambini** [comment]
@untoldengine I am sorry, but I am not sure to understand.

What should modelCreate do?
Why you create a Gravity instance inside that function?
How modelCreate is bound? (with which name?)

I am sure I could find a solution, but I need a way to understand what you are doing, or better, what you are trying to achieve.
Please share as much code as possible because there are too many missing parts to fully understand.

Thanks.

**Comment by untoldengine** [comment]
Hi @marcobambini

I was able to duplicate the issue using the GravityCpp example that you provide in your repo.

Please see the attachment. It is basically your main.cpp code example, but with added changes to highlight the issue.

Take a look at the source code in line 178. In line 180, I create a subclass of the Rectangle Class. And in line 184, I create two instances of the subclass.

Run it and you will see that the code crash because the second instance was never created.

It is a weird issue.
Thanks

[gravityissue.zip](https://github.com/marcobambini/gravity/files/6719758/gravityissue.zip)

**Comment by marcobambini** [comment]
Hi @untoldengine,

Thank you so much for the attached example. It was really helpful!

I fixed the issue with https://github.com/marcobambini/gravity/commit/7322fc2c530b11322a8dab8ae4bae2fdd4fc01a8.
It was due to an optimization introduced some months ago (lazy loading of external superclasses).
Basically, the constructor (of the external superclass) was called only the first time (that's why your second instance crashed).

Hope this helps.
Thanks for your help.

**Comment by untoldengine** [comment]
Hi @marcobambini 

Yep, that fixed the issue. 

Thank you so much. I'm almost done integrating Gravity into the Untold Engine. 
I'm planning to upload a video in the coming weeks and share with the Game Engine Developers community how easy it was to integrate Gravity. They may get interested and also use your language in their engines.

Thank you. closing this issue.

**Comment by marcobambini** [comment]
Thanks @untoldengine, please keep me updated.

**Comment by marcobambini** [comment]
Hi @untoldengine,
I just fixed a regression bug introduced to fix this issue.

Please upgrade Gravity to the latest 0.8.4 version.

**Comment by untoldengine** [comment]
Hi @marcobambini 
Thank you for the heads-up.
