### ISSUE TITLE
Regression introduced in 0.8.3 that freezes when running landpage example and 77 other unit tests

### ISSUE THREAD

**Issue by pamarcos** [marcobambini/gravity#379]
There seems to be an issue when parsing/executing classes, because testing out the sample code in the landing page lets gravity unresponsive:
https://marcobambini.github.io/gravity/#/README?id=what-gravity-code-looks-like

I've created a PR at https://github.com/marcobambini/gravity/pull/378 to add running all existing unit tests on Travis CI to prevent this from happening again.

Feel free to checkout a script I created to run all unit tests: https://github.com/pamarcos/gravity/blob/add_unit_tests_to_ci/test/unittest/run_all.sh

With this, I found the following:
* 0.8.1 runs successfully 295/295
* 0.8.2 runs successfully 294/295. `max_recursion.gravity` fails
* 0.8.3 runs successfully only 218/296. 1 failed (`max_recursion.gravity`) and 77 timed out. 7322fc2c530b11322a8dab8ae4bae2fdd4fc01a8 seems to be the root cause of this. You can check out this Travis execution to see the result: https://travis-ci.com/github/pamarcos/gravity/jobs/526026606. Surprisingly, the `max_recursion.gravity` unit test is working on the CI while on my Ubuntu 20.04 it gets killed
```
./gravity test/unittest/max_recursion.gravity
[1]    1298256 killed     ./gravity test/unittest/max_recursion.gravity
```

**Comment by marcobambini** [comment]
Oh yes you are right!
I will start investigating the issue shortly.
I hope to have a fix (and then accept your Pull Request) in few hours.
