### ISSUE TITLE
Planned event syntax

### ISSUE THREAD

**Issue by GregorMCameron** [marcobambini/gravity#386]
Hi.
I understand that at some point event callbacks are planned to be added to the language and there's already some hooks in the code for it (such as the event keyword, parse_event_declaration, gravity_instance_lookup_event etc)
I'm just interested in what the planned syntax is (curiosity + to assist anyone in submitting a pull request)

**Comment by marcobambini** [comment]
Hi @GregorMCameron, the callbacks are currently available to the C API only and I do not plan to expose them to the Gravity language.
