### ISSUE TITLE
Problems compiling without GRAVITY_COMPUTED_GOTO being set

### ISSUE THREAD

**Issue by LADSoft** [marcobambini/gravity#394]
I tried compiling gravity on Orange C and found I had to disable computed gotos (it doesn't support them at this time).   Unfortunately when I disabled computed gotos by setting GRAVITY_COMPUTED_GOTO to zero (at the same place it is set to zero for MSVC)   I got a preprocessor error: the definition of INTERPRET_LOOP in src/runtime/gravity_vmmacros.h tries to use UPDATE_STATS with a single argument.   The definition of UPDATE_STATS in the same file takes two arguments which is where the preprocessor error came from.

**Comment by marcobambini** [comment]
Thanks @LADSoft for your report.
Please retry, it should work now.

**Comment by GitMensch** [comment]
As noted in the referenced issue of the compiler: works fine now.
