### ISSUE TITLE
Runtime Error Should Report File and Line Number

### ISSUE THREAD

**Issue by mwasplund** [marcobambini/gravity#403]
It is very hard to debug runtime issues when the error message does not include the file and line number where the issue occurred.

**Comment by mwasplund** [comment]
A call stack would also be very useful. It is really hard to investigate when a shared method throws a runtime error.

**Comment by marcobambini** [comment]
@mwasplund see `gravity_callframe_dump` in gravity_vm.c
I probably should expose that function.

**Comment by marcobambini** [comment]
> It is very hard to debug runtime issues when the error message does not include the file and line number where the issue occurred.

That would require to add support for debug symbols, something that it is already in my TO DO list.
