### ISSUE TITLE
Documentation section arrow eats into section name

### ISSUE THREAD

**Issue by hrszpuk** [marcobambini/gravity#407]
The documentation website has an arrow for each section but it doesn't start in-front of the section name instead it shares the same space as the name itself. This makes the name of the sections less readable.

![image](https://github.com/marcobambini/gravity/assets/107559570/228a367c-886e-4f4c-a407-1f941048c3e1)

**Comment by marcobambini** [comment]
I think that the template should be updated.
It worked fine in the past and I don't know why it seems broken now.
Let me check if there is an upgrade to that template.

**Comment by marcobambini** [comment]
@hrszpuk fixed by https://github.com/marcobambini/gravity/commit/1f14e125c225f3785b1c2378ee45dd06fd1de960
