### ISSUE TITLE
The vulnerability is a memory leak bug located at line 440 of the file /gravity/src/compiler/gravity_parser.c

### ISSUE THREAD

**Issue by LuMingYinDetect** [marcobambini/gravity#422]
Hello, I am a graduate student specializing in static analysis of programs. Recently, while using a static analysis tool to detect issues in open-source projects, I found several defects in the project. The description of the defects can be found at the following link:https://github.com/LuMingYinDetect/gravity_defects/blob/main/gravity_detect_1.md

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/a31e74d5ddbe84d627a5db2cf6980035b97eccc2
