### ISSUE TITLE
The vulnerability is a memory leak bug located at line 46 of the file /gravity/src/compiler/gravity_ircode.c

### ISSUE THREAD

**Issue by LuMingYinDetect** [marcobambini/gravity#423]
Hello, I am a graduate student specializing in static analysis of programs. Recently, while using a static analysis tool to detect issues in open-source projects, I found several defects in the project. The description of the defects can be found at the following link:https://github.com/LuMingYinDetect/gravity_defects/blob/main/gravity_detect_2.md

**Comment by marcobambini** [comment]
Thanks @LuMingYinDetect.
Fixed by https://github.com/marcobambini/gravity/commit/fe1e2f5cb6cd2e5ea9cbeb8e48c5e93493eea0e5
