### ISSUE TITLE
gravity project needs a clear roadmap + other suggestions

### ISSUE THREAD

**Issue by abshammeri** [marcobambini/gravity#44]
I'm in love with gravity .. I can feel the chemistry between us. 

-  **Providing a clear roadmap would be awesome.**
- Improving the ecosystem by providing rich APIs < io, network , process , etc...>
- Request for fundraising .. we can help to speed up the development process.

**Comment by Dohxis** [comment]
Thumbs up for a clear roadmap!

**Comment by brandon-ray** [comment]
I am all for rich APIs, so long as they can be easily excluded for use in embedded applications.

**Comment by marcobambini** [comment]
Roadmap wiki page updated: https://github.com/marcobambini/gravity/wiki/Roadmap
any contribution is more than welcome.
