### ISSUE TITLE
Suggestion: Add something like a this keyword to classes

### ISSUE THREAD

**Issue by LennartH** [marcobambini/gravity#46]
This is a common solution for fields that are shadowed by a paremter. This may be personal preference, but I think that this
```
func init(x, y) {
	this.x = x;
	this.y = y;
}
```
looks more clean than this
```
func init(x, y) {
	_x = x;
	_y = y;
}
```

**Comment by marcobambini** [comment]
Gravity uses **self** for that purpose.

**Comment by LennartH** [comment]
Ok, good to know.

Then I would suggest to update the documentation and examples. The way _Rectangle_ is defined [here](https://marcobambini.github.io/gravity/syntax.html) and that **self** isn't listed in the reserved keywords (if it should be considered as keyword) led me to the conclusion that there isn't something like that yet.

**Comment by marcobambini** [comment]
**self** is implemented like an hidden implicit parameter and not as a reserved keyword.
