### ISSUE TITLE
What advantages Gravity provides over "face-lifted" dialects of Lua with more modern syntax?

### ISSUE THREAD

**Issue by romix** [marcobambini/gravity#48]
Could you provide some feedback regarding the advantages of Gravity over Lua-based experiments like e.g. https://github.com/richardhundt/shine or https://github.com/leafo/moonscript?

Those project translate an extended syntax (e.g. supporting classes, try/catch, etc) into a standard Lua source code or onto Lua/LuaJIT bytecode. And providing a new syntax on top of Lua is extremely easy (see Shine as an example). They do not require any changes of the Lua VM. And they can be used with LuaJIT, which gives a huge performance boost.

It would be interesting to understand why Gravity goes for its own VM and what advantages this VM provides over Lua VM/LuaJIT or Wren VM.

**Comment by romix** [comment]
Ping! :-) It seems to be the only issue without any response after 5 days. Is there any hope to get one?

**Comment by marcobambini** [comment]
Sorry for the late reply but the question you posted has not an easy answer.
They are both very interesting projects but cannot be compared to Gravity. Gravity is just born and in the near future a lot of interesting features will be added.

I really don't like to reinvent the wheel but I like the idea to create a very maintainable and efficient language that can be highly customized and extended. I am a big fan of Lua and Gravity VM performance are always compared to the highly efficient Lua VM.

I could have surely saved a lot of time just adding a Gravity like syntax over an existing VM but the result would be yet another syntax on top of Lua. The things I learned (and that I can now teach with the Internals project) during the development of Gravity and the possibility that we now have would not be possible with a shortcut.

I realize that you could probably disagree with my reply but for the challenges we faced during the development of Creo, I strongly believe that Gravity has been the right answer.

In the end the right choice would be Gravity on top of LLVM and not on top of LuaJIT that cannot run on ARM processors (it is an x86 only project) and Gravity with LLVM is in my roadmap.

**Comment by romix** [comment]
Thanks for your reply!

Quick question about the following statement:
> In the end the right choice would be Gravity on top of LLVM and not on top of LuaJIT that cannot run on ARM processors (it is an x86 only project) and Gravity with LLVM is in my roadmap.

Do you mean LuaJIT cannot run on ARM processors? If this is what you mean, it looks like apparently it can. See e.g. http://luajit.org/luajit.html and https://luajit.org/performance_arm.html But the JIT part is disabled on iOS devices due to AppStore policies, AFAIK.

And, BTW, I can totally see that your own VM may be more extensible than at least LuaJIT, which is pretty hard to extend. 

As for the GravityVM vs LuaVM/Wren VM, I'm eager to learn more about their essential differences, once you start publishing more information on your Internals project pages.

Don't get me wrong: I'm not questioning the purpose of the whole effort. Gravity and GravityVM are small and elegant. There is no doubt about that. I'm just trying to understand the "unique selling points" of Gravity when it comes to the VM part (not the language). To do that I'd like to understand the major differences between GravityVM and LuaVM/Wren VM and LuaJIT.

**Comment by marcobambini** [comment]
I didn't know that LuaJIT was ported to so many platforms. It is really an amazing technology.
I am going to close this thread, for any other question don't hesitate to open others issues.
