### ISSUE TITLE
calling null or undefined does not throw a runtime error

### ISSUE THREAD

**Issue by parro-it** [marcobambini/gravity#52]
I would expect a runtime error when I try to call `undefined` or `null` values, but instead I get a `null` value and no error.

```js
func main() {
    // "ciao"();        // RUNTIME ERROR: Unable to call object (in function main)
    // 42();            // RUNTIME ERROR: Unable to call object (in function main)
    // 42.42();         // RUNTIME ERROR: Unable to call object (in function main)

    null();             // no error thrown
    undefined();        // no error thrown
}
```

I'm using Gravity version 0.2.5 (Mar  9 2017) on OSX 10.10.5

**Comment by marcobambini** [comment]
This behavior is controlled by a GRAVITY_NULL_SILENT macro defined in gravity_value.h.
When set to 1 null and undefined (which is null under the hood) silently fail while thrown a runtime error when set to 0. When set to 1 it is like nil behavior in objc.

**Comment by parro-it** [comment]
Thank you @marcobambini. While I understand the need to keep compatibility with Apple languages, it seems to be that throw an error is a better choice here...
