### ISSUE TITLE
how to check type of functions?

### ISSUE THREAD

**Issue by parro-it** [marcobambini/gravity#53]
Given this code

```js
func half (n) {
    return n / 2;
}

func main () {
    System.print(half is Function);
    System.print(half is Object);
}
```

I will expect an output of 

```
true
true
```

But what I get is 
```
false
true
```

So, `half is Function` return false. How can I check if something is a function?

**Comment by marcobambini** [comment]
half is a Closure is the way to go
Every func is internally transformed into a Closure
