### ISSUE TITLE
How to raise an Exception?

### ISSUE THREAD

**Issue by parro-it** [marcobambini/gravity#56]
I didn't find anything in the documentation.

**Comment by lpil** [comment]
The word "Exception" doesn't appear in the codebase anywhere, so I suspect that Gravity does not have them.

**Comment by parro-it** [comment]
Maybe they are called Error. It has for sure a RuntimeError: by now as a workaround [I'm raising an error in this silly way:](https://github.com/parro-it/gravity-func/blob/master/gravity-func.gravity#L1)

```swift

func raiseError() {
    return 1 / 0;
}
```

**Comment by lpil** [comment]
I had a scan for the word error and there's no code in the repo's tests in which Gravity raises an error itself.

**Comment by ejrjohn** [comment]
Is that what was sent last night I'm not sure what I was doing.at t

**Comment by ejrjohn** [comment]
Itp1iipirks2peeld nmmmxbjrsuiriollMhsdltksjhshr458idDZcnhaujfksv XcbsjuajadhbzmnvdagfooakaifC,hsjkd .Hsffkhbjasfsg.  I don't know what I'll done but can do this all times.

**Comment by marcobambini** [comment]
There are runtime errors in the unit test, for example runtime_error1.gravity or runtime_error2.gravity raised automatically by the VM. In order to manually raise and error the idea is to the Fiber class (so error can be catch but I need to finish Fiber implementation first).

I'd like to discuss if the implementation of the traditional try/catch/finally is a good choice because I have many doubts about it.

**Comment by kazzkiq** [comment]
I think the syntax from C#/JavaScript is pretty straightforward and compatible with Gravity syntax. Example in JavaScript:


```js
function myException(message) {
   this.message = message
   this.name = 'myException'
}

try {
  var error = true
  if(error) {
    throw new myException('An error ocurred.')
  }
} catch (e) {
  e.name // returns 'myException'
}
```

JavaScript Reference Doc:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

C# Reference Doc:
https://msdn.microsoft.com/en-US/library/1ah5wsex.aspx

**Comment by marcobambini** [comment]
As a drawback, the try/catch code will add more complexity while Fiber solution is already in place:

```js
var fiber = Fiber.create({return 1/0;})
var error = fiber.try() 

System.print("Caught runtime error: " + error)
```

**Comment by parro-it** [comment]
> As a drawback, the try/catch code will add more complexity while Fiber solution is already in place:

Alternatively, it could be easier to allow functions to return multiple values? This way, errors could be managed like `go` does.

**Comment by marcobambini** [comment]
I just added a way (https://github.com/marcobambini/gravity/commit/2f8a8146879d44864019d1ceb3a1d1a660ad2071) to generate runtime errors via:
```swift
Fiber.abort("Error message here")
```

We can continue the try/catch/exception discussion to wiki: https://github.com/marcobambini/gravity/wiki/Exceptions
