### ISSUE TITLE
Example repo

### ISSUE THREAD

**Issue by parro-it** [marcobambini/gravity#57]
Today I wrote some example, just to start learning the language. 
In the hope it could be helpful to others as learning material, here is it: https://github.com/parro-it/gravity-func

By now, I implemented a `map` and a `filter` functions, I'll also try to add following ones:

* curry
* reduce
* compose
* pipe
* reverseArgs

Feel free to suggests other function you think may fit...

**Comment by marcobambini** [comment]
Thanks a lot @parro-it I added a link to your repo in the Wiki page.
