### ISSUE TITLE
Question: How it is Done??

### ISSUE THREAD

**Issue by sunel** [marcobambini/gravity#59]
Awesome Work :clap: :clap: :clap: !!!!

As many would will have or i have this question how these programming language are crafted. As Gravity been developed it would be great if you could share some of you experience by given a talk on ......

- How gravity works or how it all started ?
- Implementing small feature ?
- References or Guide or something like that  you used during the development ?

Sorry for my long post :grin:

**Comment by lodi-g** [comment]
I think all of this will be abailable here: https://marcobambini.github.io/gravity/internals/index.html

:)

**Comment by marcobambini** [comment]
I'll start posting more details in internals section pretty soon.
