### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by beders** [marcobambini/gravity#6]
Not sure about your current naming conventions yet, but can we have class names be starting with uppercase letter and functions/methods with lowercase?

`return obj0.sum() + obj1.sum() + obj2.sum() + obj3.sum() + obj4.sum2() + c4.sum1();`

is vastly more readable than:

`return obj0.Sum() + obj1.Sum() + obj2.Sum() + obj3.Sum() + obj4.Sum2() + c4.Sum1();`

**Comment by marcobambini** [comment]
You are absolute right and I tried to adhere to that naming convention.
Can you please let me know where have you find that code so I can fix it?
Thanks.

**Comment by pgporada** [comment]
This may help you find all the functions unless you'd want to take a PR from me.
```
cd gravity
grep -r "\.[A-Z].*()" *
```

```
test/classes/base_object_methods.gravity:	r = v.String();					if (r != v)			return "-7 (" + r + ")";
test/classes/base_object_methods.gravity:	r = bar.String();				if (r != "bar")		return "-9 (" + r + ")";
test/classes/base_object_methods.gravity:	r = 0.1.String();				if (r != "0.100000")	return "-10 (" + r + ")";
test/classes/base_object_methods.gravity:	r = null.String();				if (r != "null")	return "-11 (" + r + ")";
test/classes/base_object_methods.gravity:	r = true.String();				if (r != "true")	return "-12 (" + r + ")";
test/classes/base_object_methods.gravity:	r = main.String();				if (r != "main")	return "-13 (" + r + ")";
```

**Comment by marcobambini** [comment]
Well, it is a bit more complicated than that.
Method String has the same name as the class String in order to support automatic conversion between different types. This should be the only exception to the naming convention as noted by @beders
