### ISSUE TITLE
Thread safety in Gravity???

### ISSUE THREAD

**Issue by GreenJoey** [marcobambini/gravity#66]
I just saw your repo and the first things that caught my attention were **concurrent** and **scripting language**. And the query is: Are threads implemented?? Are they OS native or VM native?? And how is thread safety implemented?? And the ever popular: Is there andy kind of Global Interpreter Lock??

**Comment by marcobambini** [comment]
Concurrent means that coroutines can be executed via fibers [https://marcobambini.github.io/gravity/fibers.html](https://marcobambini.github.io/gravity/fibers.html) 
It is cooperative threading, preemptive threading is not yet implemented.

**Comment by GreenJoey** [comment]
In other language async concurrent programming is implemented but threading in the traditional sense is still not implemented??

 
N.B: Sorry, I am still a beginner

**Comment by marcobambini** [comment]
Well, it really depends on the language but generally speaking it is problem that can be solved adding a lot of complexity to the code base. In the future we could add async calls to Gravity but we have others priorities now.
