### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by arjunmenon** [marcobambini/gravity#69]
Hey
Congrats on releasing a new language.

I wanted to ask you, why a Ruby-like syntax which in my opinion is more lovely, never makes the cut. I often pray sheepishly if ever a new language comes out, if it could be readable like Ruby.

Imagine my pique when developers like you address such practical scenario so elegantly, end up with curly braces. 

_Why-oh-why?_

**Comment by marcobambini** [comment]
I agree with the beauty of a Ruby-like syntax but our target was a C like syntax (so Javascript, Java, Swift, C# and many many others)... in this way people familiar with both low level development (C,C++), web development (javascript) and mobile development (Swift, C#, Java) will find a more familiar syntax in Gravity.

I also believe that the beauty of a language is 50% syntax and 50% under the hood.
Erlang for example has a terrible syntax with an awesome technology under the hood.

**Comment by aeosynth** [comment]
@arjunmenon [crystal](https://github.com/crystal-lang/crystal) is a new-ish compiled language with ruby inspired syntax
