### ISSUE TITLE
VALUE_FROM_CLOSURE macro missing

### ISSUE THREAD

**Issue by ccntrQ** [marcobambini/gravity#7]
I wanted to try fiddling around with the embedding api allthough i think the
`VALUE_FROM_CLOSURE` macro mentioned in the api docs seems to be missing from the source. Can you help me out?

**Comment by marcobambini** [comment]
There is no VALUE_FROM_CLOSURE nor VALUE_FROM_FUNCTION macros.
Just use VALUE_FROM_OBJECT and pass your closure/function as argument.
For example: VALUE_FROM_OBJECT(closure).

**Comment by ccntrQ** [comment]
The macro is mentioned here:
```
docs/api.html:108:      gravity_class_bind(c, "myfunc", VALUE_FROM_CLOSURE(closure));
```
I'll try using the other marco. Thanks a lot

**Comment by marcobambini** [comment]
Thanks for pointing it out, I fixed the doc.
