### ISSUE TITLE
main() return value

### ISSUE THREAD

**Issue by probandula** [marcobambini/gravity#75]
Hey there,
I'm playing with gravity for a while now and I really like it :)
But what I wonder is if the return value of the `main()` function shouldn't be the return value of the program, so if I write `return 5;` I assume the program to exit with error code 5. Maybe It's my fault or it's a design decision.
Nice project, have a good time

**Comment by marcobambini** [comment]
Hi, main returns a value in a C program, Gravity simply uses a different convention, it returns what the user decides to return explicitly.

**Comment by probandula** [comment]
Ok, is there a way to exit with a specific code? Something like `System.exit(5)`?

**Comment by marcobambini** [comment]
From where?
From the gravity command line utility?
Or from the main function in your c code?

**Comment by probandula** [comment]
I want to abort the execution in my gravity code so that my last exit code in my shell (`$?`) gets that.

**Comment by marcobambini** [comment]
I just added a System.exit(n) method: https://github.com/marcobambini/gravity/commit/db7c9eb25b1c08df9daa8d50f760a07fd4efb2dc

**Comment by probandula** [comment]
Very nice, thanks :)
