### ISSUE TITLE
Purpose: Closures `apply` method

### ISSUE THREAD

**Issue by parro-it** [marcobambini/gravity#79]
Sometimes is necessary to dynamic call a function by passing its arguments as a list. In javascript, we have Function.apply method for this. 

I didn't find a native way to implement this, so I reverted to do this weird trick in [gravity-func](https://github.com/parro-it/gravity-func/blob/master/gravity-func.gravity#L46):

```swift
func apply (fn, args) {
    if (args.count == 1) return fn(args[0]);
    if (args.count == 2) return fn(args[0], args[1]);
    if (args.count == 3) return fn(args[0], args[1], args[2]);
    if (args.count == 4) return fn(args[0], args[1], args[2], args[3]);
    if (args.count == 5) return fn(args[0], args[1], args[2], args[3], args[4]);
    if (args.count == 6) return fn(args[0], args[1], args[2], args[3], args[4], args[5]);
}
```

I think a native method that allow for any number of arguments could be useful to have.

**Comment by hallzy** [comment]
you mean like `_args`?

See: https://marcobambini.github.io/gravity/functions.html

`_args` is a built in keyword that is a list of the arguments passed to the function

**Comment by marcobambini** [comment]
@parro-it does apply should have two parameters? The self object and the array of arguments.

**Comment by parro-it** [comment]
@marcobambini yes that's perfect!

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/10c09fc5a9caf5df4298779d3bd321358ec23757

**Comment by parro-it** [comment]
Thank you @marcobambini, I'll add it to the documentation
