### ISSUE TITLE
Will extending classes be supported?

### ISSUE THREAD

**Issue by brandon-ray** [marcobambini/gravity#8]
I hope I haven't missed this but I didn't see anything about class extension in the documentation, are there any plans for this or is it already supported in any way?

I have an interest in using Gravity for game scripting and class extension would be very useful.

**Comment by marcobambini** [comment]
It will be available pretty soon and it is easy to implement, I am just looking for a nice syntax to use.
I was thinking about:
MyFoo extends Foo {
    ...
}

**Comment by brandon-ray** [comment]
Awesome, that sounds good to me.

Also great work so far! Excited to use this at some point.
