### ISSUE TITLE
Getting rid of the warning: redefinition of typedef

### ISSUE THREAD

**Issue by marcobambini** [marcobambini/gravity#84]
When compiling Gravity there are some warnings that really annoy me.
Anyone know how to get rid of them?

For example:
 ```
warning: redefinition of typedef
      'gravity_class_t' is a C11 feature [-Wtypedef-redefinition]
} gravity_class_t;
```

**Comment by hallzy** [comment]
I don't get any warnings when I compile. I even just did a clean and remade it to double check. Strange.

The only thing that I see it could be is in `src/shared/gravity_value.h`

Line 149 has a typedef that defines gravity_class_t, and then 314 defines it again?

**Comment by marcobambini** [comment]
gravity_value_t is defined only once in gravity_value.h

**Comment by hallzy** [comment]
Your warning above said `gravity_class_t`, not `gravity_value_t`.

Line 149 has:

```c
typedef struct gravity_class_s    gravity_class_t;
```

and 314 is the bottom end of:

```c
typedef struct gravity_class_s {
...
...
} gravity_class_t;

```

Perhaps the compiler is interpreting this as a redefinition?

**Comment by marcobambini** [comment]
Yes you are right.
I need to define gravity_class_t to define the isa pointer:

```swift
typedef struct gravity_class_s gravity_class_t;
typedef struct {
	gravity_class_t            *isa;     // EVERY object must have an ISA pointer (8 bytes on a 64bit system)
	union {                              // union takes 8 bytes on a 64bit system
		gravity_int_t      n;        // integer slot
		gravity_float_t    f;        // float/double slot
		gravity_object_t  *p;        // ptr to object slot
	};
} gravity_value_t;

```
The same isa pointer is then used inside gravity_class_t declaration:
```swift
typedef struct gravity_class_s {
	gravity_class_t       *isa;      // to be an object
	gravity_gc_t          gc;       // to be collectable by the garbage collector
	
	gravity_class_t       *objclass;       // meta class
	const char            *identifier;       // class name
	bool                  has_outer;       // flag used to automatically set ivar 0 to outer class (if any)
	bool                  is_struct;       // flag to mark class as a struct
	bool                  is_inited;       // flag used to mark already init meta-classes (to be improved)
	bool                  unused;       // unused padding byte
	void                  *xdata;       // extra bridged data
	struct gravity_class_s *superclass;       // reference to the super class
	gravity_hash_t       *htable;       // hash table
	uint32_t             nivars;       // number of instance variables
	//cstring_r          debug;       // ivar index to name debug info
	gravity_value_t       *ivars;       // static variables
} gravity_class_t;
```
so I need a forward definition.

I wondering if I could use struct gravity_class_s * as isa pointer.

**Comment by marcobambini** [comment]
Fixed the gravity_class_t warning by https://github.com/marcobambini/gravity/commit/0e023c35ecf304767b1e79aab65ffea14135649b
Now I should try to get rid of the gravity_hash_t redefinition warning (which is a different case).

**Comment by hallzy** [comment]
good to know... Strange that I don't seem to get any of these warnings though.
