### ISSUE TITLE
Shebang for Gravity

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#86]
will there be any consideration to allow the common `#!` shebang for gravity (for example, using `#!/bin/gravity` at the top of a gravity source file to tell the shell to execute that file using gravity)?

Currently, because the comments in gravity are C-Style, the `#!` doesn't work. The shell understands that it needs to run the file using gravity when you use `#!/bin/gravity` (assuming your gravity binary is in `/bin`), but once gravity goes to parse the file it fails because it (rightly) doesn't understand what `#!` is.

Right now if you want to do a shebang like thing for gravity, you have to use the trick that users of Go are using right now which is to use `//bin/gravity $0 $@; exit $?` instead of `#!/bin/gravity`.

Obviously, that is way uglier and harder to remember.

I suppose that it could be resolved by modifying the parser to interpret `#!` on line 1 of a gravity file as a comment... and line 1 only (interpreting just `#` probably doesn't work, since `#` is used in gravity for other things like `#unittest` and there is always the possibility that such a line will actually be the first line of a file.

I however see no reason for `#!` to be on the first line except for using a shebang.

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/7f85d8441b3360a24d462908882d19f1f0c35f0a
