### ISSUE TITLE
logical xor?

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#87]
Before anyone wonders why I am asking (since, as far as I know, a logical xor does not exist in any other language) just want to say that I have looked for a legitimate reason why a logical xor does not exist in other languages. The best answer I have found is that it is rare enough that there is no point.

Other such answers are that "It is easy to make a logical xor out of other logical operators"... Yes, this is true (assuming `^^` is logical xor: `x ^^ y` is the same as `!x ^ !y`... since the act of taking the `not` of a value makes it a boolean value), but it looks uglier, and you can actually quite easily make your own logical or with ands as well... (ie `x || y` is the same as `!(!x && !y)`... which is in fact easier to do than an xor if you only use logical operators: `x ^^ y` is the same as `(x && !y) || (y && !x)`), so I am not sure that I buy that answer.

With that out of the way, I thought I would ask if gravity would perhaps be the first language I know of to support a logical xor operator?

**Comment by marcobambini** [comment]
Gravity like Swift supports bitwise xor via the ^ operator: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AdvancedOperators.html

**Comment by hallzy** [comment]
I was referring more to a logical xor as apposed to a bitwise xor... so we have a logical and bitwise and: `5 && 4` evaluates to `true` while `5 & 4` evaluates to `4`...

Similarly I was wondering about a logical xor (ex logical xor: `5 ^^ 4` evaluates to `false` while bitwise xor: `5 ^ 4` evaluates to `1`)

**Comment by marcobambini** [comment]
I am sorry but I am not sure to understand... we have bitwise xor **^** and not logical xor. Are you proposing to introduce it?

**Comment by hallzy** [comment]
Sorry I wasn't clear... Yes, I was just wondering if it would be something you would consider adding. I am aware that gravity does not have a logical xor, only a bitwise xor.

I just thought it might be an interesting idea given that it could be handy and (as far as I know) no other language supports it.

I get it if you don't want to add it or if you think it would be a stupid thing to add, but I thought I would bring it up.

**Comment by marcobambini** [comment]
Even if I really appreciate your effort it seems a rarely used operator... what do you think about skip it for now? I am not against new operators... but only if they could be really useful :-)

**Comment by hallzy** [comment]
Sounds good :)
