### ISSUE TITLE
Programmatically accessing ivars

### ISSUE THREAD

**Issue by marcobambini** [marcobambini/gravity#92]
I need a way to programmatically access ivars from an instance.
Initially I thought about some inelegant way like
```swift
instance.ivar[0]
```
then I realized I could just add the load/storeat methods to the instance class in order to be able to read/write instances in a nicer way:
```swift
instance[0]
```

What do you think about it?

I'd like also to have a way to count the number of ivars contained in an instance.
Initially I thought about:
```swift
instance.count
```
but what about if Class instance has a count property?
Any smart idea about how I could minimize name collision in this case?

**Comment by parro-it** [comment]
@marcobambini what are exactly ivars? Are them some sort of slots where are stored instance variables?

If so, I would prefer to access them by using ad-hoc methods of the Class, e.g.:

```swift
Class.setProperty(0, 'someValue'); 
Class.getProperty(0); 
Class.getPropertiesCount(0); 
```

**Comment by parro-it** [comment]
Syntax such `instance[0]` and `instance.count` make me think at first that I'm dealing with some kind of list or array... but it's just my thought, it's probably subjective...

**Comment by marcobambini** [comment]
Yes I agree it is a weird syntax, but your syntax would be more OO with:
```swift
// instance properties
instance.setProperty(0, 'someValue');
instance.getProperty(0);
instance.countProperties();

// class properties
Class.setProperty(0, 'someValue');
Class.getProperty(0);
Class.countProperties();
```

**Comment by Jezza** [comment]
Could you use a .props accessor? 

So, instance.props[0] = "blah"?
