### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by marcobambini** [marcobambini/gravity#93]
I think we should start discussion about how to expose introspection.
Ruby for example uses this syntax: http://stackoverflow.com/questions/2492730/how-do-i-introspect-things-in-ruby

Can we do better?

**Comment by brandon-ray** [comment]
I think some sort of function or property on the object its self is good. That or a static function on the Object class its self, something like ```Object.keys(obj);``` in Javascript.

**Comment by InusualZ** [comment]
Yeah, I was thinking on the same. `Object.methods(obj)` and `Object.fields(obj)`

**Comment by Jezza** [comment]
I don't like the idea of introspection via external means.
It seems like too much indirection.

For example, in Java, you could access the class constant via .class or getClass(), could we try the same thing? 

Otherwise, you're banking on the hope that someone's going to have to look it up.

**Comment by Jezza** [comment]
As in, lookup how to do it.

**Comment by kjk** [comment]
One of the designers of Dart has put a lot of thought into reflection design and is a proponent of mirror-based reflection (as opposed to Python's/Java's/Ruby's baking of reflection API into object itself).

A good start on his ideas is https://gbracha.blogspot.com/2010/03/through-looking-glass-darkly.html and the paper and screencast it links.

Dart uses those ideas (https://www.dartlang.org/articles/libraries/reflection-with-mirrors).

While Go doesn't talk about mirrors, they use the similar idea of having reflection system separate from core values https://golang.org/pkg/reflect/

.NET also evolved its reflection API towards the model of separation reflection from being API of the core objects to a separate thing (https://blogs.msdn.microsoft.com/dotnet/2012/08/28/evolving-the-reflection-api/), which is the core idea.

**Comment by marcobambini** [comment]
All Objects now responds to the following methods:
```
Object.introspection();
Object.methods();
Object.properties();
```

Each method support two optional parameters:
- param1 a Bool value (default false), it set to true returns extended information
- param1 a Bool value (default false), if set to true it doesn't scan super classes

Result can be a List or a Map (in case of param1 set to true).
