### ISSUE TITLE
cannot compile it by mingw

### ISSUE THREAD

**Issue by charlinone** [marcobambini/gravity#94]
src/utils//gravity_utils.o:gravity_utils.c:(.text+0x16d): undefined reference to `getline'

getline is not stardard function.

**Comment by hallzy** [comment]
I have referenced a commit on my fork with the link above ^^

can you see if that works? I tried replacing getline with fgets instead.

**Comment by marcobambini** [comment]
I prefer to write a replacement function for Windows only , getline is pretty solid on POSIX systems.
This fixes the build (I am sorry for that) https://github.com/marcobambini/gravity/commit/46834d02275d1e081bf1ea842f85760959d80388

**We really need a way to add Windows target build to Travis!**
